### ISSUE TITLE
[Windows, Nightly 49] Window draw size too small with Tab Center

### ISSUE THREAD

**Issue by eleemoz** [bwinton/VerticalTabs#105]
![gutter](https://cloud.githubusercontent.com/assets/13700135/14999794/6306e518-1140-11e6-8c7a-99832d1e9dc1.png)

For some/all (still trying to test) tabs/pages, the very bottom gets cut off. This hides part of the website, or any horizontal scroll bar, and the "status" text (e.g., URL preview when you hover over a link).

**Comment by brsmith-mozilla** [comment]
I am also seeing this issue on mac.

**Comment by BrDon** [comment]
The Moz' IRC Cloud's type-one's-message-box, normally at the bottom, seems to be obscured by the new Tab Center.   Previous messages in that IRC channel are fine and visible as they are above the box, but the actual box to type one's message is not.

**Comment by gregglind** [comment]
(this is happening on OSX El Capitan as well.  This bug says windows specific.)
