### ISSUE TITLE
After disabling Tab Center my tabs are still vertical, but displayed in the usual place above the content

### ISSUE THREAD

**Issue by bobsilverberg** [bwinton/VerticalTabs#114]
I enabled Tab Center from Test Pilot and then disabled it. After disabling my tabs still show up as a vertical stack, but they occupy the top of the browser, where they would normally be if they were horizontal. See the screenshot:

![screenshot 2016-05-05 15 45 15](https://cloud.githubusercontent.com/assets/142755/15055040/7f59798a-12d8-11e6-9b79-9659a8f761e7.png)

I am using Firefox 46.0 on OS X 10.11.4. I also have `Tab Mix Plus 0.4.2.2` installed.

**Comment by bobsilverberg** [comment]
I restarted Firefox and tried it again and the same thing happened, but now I'm on 46.0.1. Here is the entire contents of the Browser Console from before I enabled Tab Center until after I disabled it:

```
no element found request:1:1
no element found request:1:1
Warning: attempting to write 8098 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
Warning: attempting to write 5534 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
TypeError: tabBar.mTabstrip.setFirstTabInRow is not a function tab.js:547:7
TypeError: this.mTabstrip.setFirstTabInRow is not a function
 changecode.js line 179 > eval:11:774
no element found request:1:1
no element found request:1:1
TypeError: tabBar.mTabstrip.setFirstTabInRow is not a function
 tab.js:547:7
TypeError: tabBar.mTabstrip.setFirstTabInRow is not a function
 tab.js:547:7
Could not read chrome manifest 'file:///Applications/Firefox.app/Contents/Resources/chrome.manifest'.
Warning: attempting to write 5276 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
Warning: attempting to write 7899 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
DELETE 
XHR 
https://testpilot.firefox.com/api/experiments/3/installations/80fd86ad-93f7-9640-956b-3d96353db3d4 [HTTP/1.1 410 GONE 167ms]
```

**Comment by bobsilverberg** [comment]
Note that if I disable Tab Mix Plus the problem goes away, as do the errors that were seen above in the Browser Console.

**Comment by bwinton** [comment]
Hmm…  So apparently those add-ons are incompatible (which isn't totally surprising, because XUL addons. :wink:)  @johngruen Any thoughts on what we can do here (and with the other add-ons that don't work well with Tab Center?  Pop up a warning maybe?  Put something in the Test Pilot description listing known incompatibilities?

**Comment by wresuolc** [comment]
We think this is fixed in the latest versions.  (non-compatible add-ons aside)
