### ISSUE TITLE
Tab center redraws screen to small

### ISSUE THREAD

**Issue by rpappalax** [bwinton/VerticalTabs#115]
Once I enabled tab center, my screen looks like this...

![tab_center](https://cloud.githubusercontent.com/assets/3699494/15055445/80775e48-12c1-11e6-825f-34ec7065ea17.png)

I'm on OSX w/ Firefox 45.02

tried refreshing tabs, re-starting browser, etc. but it's stuck in this mode.  Because the screen-size is so tiny, I'm unable to turn off tab center either.  Is there an alternative way to do it?

**Comment by bwinton** [comment]
Hmmm…  Scroll a lot?  :wink:

(You can turn it off from about:addons, but that will also require a bunch of scrolling.  Oh, or you can go to your Profile directory at `~/Library/Application\ Support/Firefox/Profiles/<something>.<something>/extensions/` and delete the `tabcentertest1@mozilla.com` file.)

**Comment by bwinton** [comment]
Also, if you can let me know a) if there's anything suspicious looking in the Browser Console, and b) which other add-ons you have installed, that would be very helpful!

**Comment by rpappalax** [comment]
Browser console:
downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:0) source: resource://testpilot-addon/data/OpenSans-Regular.ttf panel.css:7:12
TypeError: notificationBox.hasAttribute is not a function tiletabs-browser.js:3319:14
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.12.13
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
FBO Texture Target: TEXTURE_2D
AJS.Confluence: run binder components batch.js:436:164
Drag and Drop: requesting translation batch.js:436:164
DragAndDropUtils: computed cache URL: /s/2037/5/1.0.8/_/plugins/drag-and-drop/i18n.action?locale=en_GB batch.js:436:164
undefined app.js:9:2450
[1000]</<.initialize/<() app.js:9

OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.12.13
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
FBO Texture Target: TEXTURE_2D

**Comment by bwinton** [comment]
Ooh, are you also using TileTabs?  I wonder if that's interacting poorly with TabCenter?

**Comment by rpappalax** [comment]
they're pretty handy but i can disable them if need be.

**Comment by rpappalax** [comment]
actually, it's Tab Groups Helper

**Comment by bwinton** [comment]
Ah, good to know…

**Comment by rpappalax** [comment]
OK, I nuked both Tab Groups and Tab Groups Helper and restarted browser, and it works fine now.

**Comment by nielsdg** [comment]
Experiencing this problem as well. Of the aforementioned addons, I only use Tile Tabs; disabling it solves the problem.

**Comment by bwinton** [comment]
Will be "fixed" in #234.
