### ISSUE TITLE
New Tab button at the top feels so far away

### ISSUE THREAD

**Issue by pdolanjski** [bwinton/VerticalTabs#117]
Having the New Tab button at the top of the VerticalTab interface feels like more work than normal since my cursor is often near the button of the tab list when I choose to create a new tab.  
I wish there was a way to create a new tab close to where-ever my cursor is in the tab list.

This may entirely just be a personal preference, however.

**Comment by bwinton** [comment]
Ctrl-T.  :wink:

We did have it at the bottom in initial versions, but ran into problems with previous rounds of user testing…

**Comment by pdolanjski** [comment]
Fair enough.  If user testing suggests the location works, so be it!
