### ISSUE TITLE
Make sidebar animation faster

### ISSUE THREAD

**Issue by marco-c** [bwinton/VerticalTabs#118]
This is a shortcoming of the sidebar compared to the tab strip.
In the tab strip, switching to another tab is immediate.
In the sidebar, switching to another tab requires you to wait for the sidebar to appear.

**Comment by bwinton** [comment]
Well, that sort of depends…  😀
If you use the keyboard, it's immediate in both cases.
If the tab is visible on the top, then it's faster.
If the tab isn't visible on the top, then it's quite a bit slower to scroll until it is visible.
In either case, you can click without waiting for the sidebar to open.  :wink:

**Comment by marco-c** [comment]
When you have a few tabs open from the same website, you have to wait for the sidebar to open in order to read the title of the pages and click on the one you actually want.

**Comment by bwinton** [comment]
Touché.  :)

**Comment by johngruen** [comment]
@marco-c we're gonna hold off on most polish changes until we get end user feedback

**Comment by johngruen** [comment]
@marco-c gonna rely on user feedback to set speed. You are a user of course, but i mean multiple users :)
