### ISSUE TITLE
Add Test Pilot Information to Add-on description field

### ISSUE THREAD

**Issue by javaun** [bwinton/VerticalTabs#119]
ASAP, we need to add this to the description field in the Tab Center add-on (all addons must have this if they're ours and connected to our policies)

1. This is a Test Pilot experiment.
2. add the testpilot.firefox.com URL

![add-ons_manager](https://cloud.githubusercontent.com/assets/126270/15058145/b40ea320-12e8-11e6-9d4d-61065ae2d5ed.png)
![add-ons_manager](https://cloud.githubusercontent.com/assets/126270/15058207/f5931164-12e8-11e6-897a-18572686f738.png)

**Comment by javaun** [comment]
It's enough to say "Learn more about this Test Pilot experiment at https://testpilot.firefox.com" as we do for Activity Stream

**Comment by pdehaan** [comment]
I think this is already added via https://github.com/bwinton/VerticalTabs/commit/e43bec6f7bc3f3ec3b5577986ec1c7c687691f3a
It looks like that commit landed the day after the last release.

**Comment by bwinton** [comment]
Okay, I'll push out a new release now to fix it.

**Comment by bwinton** [comment]
Fixed by 5c109c3dc751fab72602b86ecfb2765e5599e110

**Comment by pdehaan** [comment]
Verified in 1.14 via Test Pilot:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/15060979/dd556326-12e4-11e6-8117-fec7e2c5a1bd.png)
