### ISSUE TITLE
TabCenter prevents VimFx extension from working

### ISSUE THREAD

**Issue by hwine** [bwinton/VerticalTabs#120]
At least in developer edition (Fx 48). While tab center is enabled, none of the "normal" VimFx keystrokes work.

VimFx is at [akhodakivskiy/VimFx](https://github.com/akhodakivskiy/VimFx), I'm on v0.14.1

**Comment by lundjordan** [comment]
it works for me. I am using VimFx but on ff beta 47.0b4.
I have had vimfx stop working for me occasionally but ff restart fixes it. I haven't confirmed tab center to be at fault for that though.

**Comment by hwine** [comment]
Okay - it now works on aurora for me in 48.0a2 (2016-05-10) 💯
