### ISSUE TITLE
scrolling of tabs resets automatically 

### ISSUE THREAD

**Issue by bteiger** [bwinton/VerticalTabs#121]
With a long list of open tabs active picking one from the middle or the bottom end of the list will force the tab to jump to the bottom of the list once the page is loaded or the tab is selected.  

The location of the scroll bar should not change when a tab is selected.  

This creates a problem when switching from one tab to another, especially if the two tabs are in a longer list and near the end of the open tabs.

OS X 10.11.4 - Firefox 46.0.1

**Comment by bwinton** [comment]
Possibly fixed by #153?  Can you re-test to see if it's better now?

**Comment by bwinton** [comment]
Oh, wait, I think this was _actually_ fixed by #250…
