### ISSUE TITLE
Pin sidebar button uses wrong color on Linux

### ISSUE THREAD

**Issue by callahad** [bwinton/VerticalTabs#123]
Nightly, default Firefox theme, Dark DevTools theme.

![sidebar](https://cloud.githubusercontent.com/assets/24193/15063475/38b0bca4-1310-11e6-95f8-eae9d2ec7b0f.png)

Switching to the light DevTools theme fixes this... but I don't want the light DevTools theme.

**Comment by mikeconley** [comment]
Actually this is true in Windows as well:

![pin](https://cloud.githubusercontent.com/assets/195042/15083147/a2321586-1399-11e6-9f83-d670ba3aed9f.png)

**Comment by bwinton** [comment]
Ooh, another thing that will be fixed by #132!
