### ISSUE TITLE
No indication of Private Window on Linux

### ISSUE THREAD

**Issue by callahad** [bwinton/VerticalTabs#126]
Since we don't draw our own window chrome on Linux, there's no Private Browsing badge for me to reference.

Maybe we could invert the color scheme of the sidebar, similar to Fennec's dark-gray-and-purple scheme for Private Browsing?

**Comment by Riscky** [comment]
when the tab center is expanded you can see the privacy badge next to the new tab button:

![privacybadge](https://cloud.githubusercontent.com/assets/15868836/15192257/b40049ea-17b8-11e6-9138-5700c3b2c117.png)

**Comment by SonRiab** [comment]
In Fullscreen Mode on Mac OS there is no indication too.
<img width="1280" alt="bildschirmfoto 2016-05-12 um 13 54 01" src="https://cloud.githubusercontent.com/assets/1729226/15213754/63090252-1849-11e6-820e-972f77c56098.png">
<img width="1280" alt="bildschirmfoto 2016-05-12 um 13 54 26" src="https://cloud.githubusercontent.com/assets/1729226/15213755/6309a838-1849-11e6-9e73-40d6ec33a0bc.png">

**Comment by bwinton** [comment]
Ooh, as per #230, I think this is fixed…  (I'm not sure about MacOS Full-screen mode, though…)

**Comment by bwinton** [comment]
(No, not fixed in Mac.)

**Comment by thunderdome2** [comment]
Hello.

I'm using Firefox under Debian Jessie with KDE (in french language) as desktop environment. As you on this screenshot, the Incognito mode icon is not visible:
![image](https://cloud.githubusercontent.com/assets/27619936/25803082/92329692-33f5-11e7-8fba-1fb3f39330ad.png)
A workaround could be changing the address bar color, like on Chrome. But I suppose this change is not concerning only the Tab Center addon, but Firefox by itself.
