### ISSUE TITLE
Right-click menu on toolbar items is truncated

### ISSUE THREAD

**Issue by callahad** [bwinton/VerticalTabs#128]
Possibly related to #50 

![rightclick](https://cloud.githubusercontent.com/assets/24193/15063811/ded8269c-1312-11e6-80d6-6c6dd04e5200.png)

The "Move to Menu" and "Remove from Toolbar" options are not present.

**Comment by bwinton** [comment]
Is there anything suspicious in the Browser Console?  (Also, can you reproduce it on a clean profile, or could it be a conflict with another add-on?)

**Comment by callahad** [comment]
Yep, repros on OS X and Linux on a clean profile. I don't immediately see anything that sticks out in the Browser Console. I *am* using Nightly, if that changes things.

**Comment by bwinton** [comment]
Hah!  Turns out it was code from 4 years, 10 months ago…  7a9dc4bf74af594b7813c1d12a69ae91084116a8
