### ISSUE TITLE
"New Window" and other options are removed from the Firefox menu

### ISSUE THREAD

**Issue by marco-c** [bwinton/VerticalTabs#129]

**Comment by bwinton** [comment]
I suspect this is due to another add-on you have.  Can you see if there's anything in the Browser Console that looks suspicious?

**Comment by marco-c** [comment]
> I suspect this is due to another add-on you have.

It reappeared once I disabled the vertical tabs addon (or Tab Center, I'm not sure what the official name is :smile:).

> Can you see if there's anything in the Browser Console that looks suspicious?

I'll re-enable it later and check.

> ETA: What do you mean by "the Firefox menu"?

The hamburger menu.
