### ISSUE TITLE
Remove ellipsis overflow.

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#13]
From @phlsa.
(Unknown: Where to remove ellipsis from…  ;)

**Comment by phlsa** [comment]
![snip_20160329181646](https://cloud.githubusercontent.com/assets/514315/14125668/6ad7437c-f5da-11e5-8457-0fc8dae26351.png)

**Comment by phlsa** [comment]
Removing the »crop« attribute from the .tab-label element seems to do the trick.
We can then use a fade out (e.g. by overlaying the text with a gradient), since we know the background color of tab center.

**Comment by phlsa** [comment]
Re-opening this since navigating with a tab resets the attribute to show the ellipsis.
