### ISSUE TITLE
verticaltab pin button stopped working until restart

### ISSUE THREAD

**Issue by escapewindow** [bwinton/VerticalTabs#133]
I had my verticaltabs not-autohide by clicking the top right icon that looks like a pushpin.

This morning, I thought I updated Nightly, but I failed to restart, and during that time the verticaltabs pushpin icon a) unclicked and b) stopped being clickable, resulting in autohide behavior.

Looks like there was also a release of VerticalTabs last night as well.  I don't remember having this issue on previous Nightly updates, so that may be part of the reason.

This seems like an edge case now, but if it happens regularly on VerticalTab update, people may hit it on a recurring basis.

**Comment by escapewindow** [comment]
Possibly related to https://github.com/mozilla/testpilot/issues/714 ?

**Comment by wresuolc** [comment]
We think this is related to #226
