### ISSUE TITLE
Ctrl+Tab doesn't scroll tab list to keep foreground tab in view

### ISSUE THREAD

**Issue by theres-waldo** [bwinton/VerticalTabs#136]
If I have enough tabs for the tab list to be scrollable, and I Ctrl+Tab past the last one that's currently in view, the tab list isn't scrolled to keep the foreground tab in the visible part of the tab list. I would expect it to.

**Comment by ericawright** [comment]
Also related -- when clicking "New Tab" or Ctrl+t when scrolled down on the list, it does not scroll up to the new tab.
