### ISSUE TITLE
Weird unicode text on page title

### ISSUE THREAD

**Issue by osunick** [bwinton/VerticalTabs#144]
Repro: install Tab Center and visit an experiment page on testpilot.firefox.com

screen shot here- https://www.evernote.com/shard/s3/sh/bf3f2560-af38-42e2-ae87-83246ca9c3e7/ee84a96f17b0ae021559351109aabd56

**Comment by johngruen** [comment]
I think this is test pilot?

**Comment by johngruen** [comment]
@osunick can you try to repro this with tab center uninstalled

**Comment by wresuolc** [comment]
I can reproduce this without tab center.  I filed https://github.com/mozilla/testpilot/issues/875 for Test Pilot
