### ISSUE TITLE
Customization mode doesn't work properly.

### ISSUE THREAD

**Issue by fx4waldi** [bwinton/VerticalTabs#154]
In customization mode all toolbars are hidden (tabs sidebar, navigation bar, etc.).

**Comment by m3adow** [comment]
Same here, Win 7 Professional, Firefox 46.01.

Before:
<img src="https://cloud.githubusercontent.com/assets/1872304/15174463/1d7a9ee0-1762-11e6-91fb-72326742730f.png" width="80%" height="80%" />
After:
<img src="https://cloud.githubusercontent.com/assets/1872304/15174464/1d96548c-1762-11e6-942f-7d9ca73d55e8.png" width="80%" height="80%" />

**Comment by bwinton** [comment]
Resolved dupe of #168…
