### ISSUE TITLE
In Full Screen mode, URL bar still half visible

### ISSUE THREAD

**Issue by tux3** [bwinton/VerticalTabs#155]
With Full Screen on, the URL bar doesn't hide entirely, which is a somewhat interesting bug, since it's still fully functional and almost useful!

![The problem in all its 1366x768 glory](https://cloud.githubusercontent.com/assets/5155966/15163640/f51ae520-1709-11e6-9380-2f156d3ec678.jpg)

There's also this tiny two pixel gap that above the tabs that only appears in full screen mode, although that's barely noticeable.
I'm on Linux x64 running KDE5, and I don't have any UI customization addon except Personas and Test Pilot.

**Comment by johngruen** [comment]
@tux3 closing as a dupe! We're working on it!
