### ISSUE TITLE
On open new tab, the dropdown is not shown, take advantage of it?

### ISSUE THREAD

**Issue by Noitidart** [bwinton/VerticalTabs#157]
When we first open a new tab, the dropdown that shows after we start typing in the URL bar, with hints,is not shown. Did any ideas come up on taking advantage of that space? Maybe show a small one?

I did a mockup/brainstorm here - https://github.com/Noitidart/AppLauncher

**Comment by johngruen** [comment]
@Noitidart I think this bug should be filed on universal search. Closing here for now, feel free to reopen if I'm mistaken. Thanks for your help!

https://github.com/mozilla/universal-search

**Comment by Noitidart** [comment]
Thanks :) Moved to here - https://github.com/mozilla/universal-search/issues/212
