### ISSUE TITLE
Visual design for Tab Center

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#16]
From @phlsa.
Needs mockup.

**Comment by bwinton** [comment]
Current Developer Edition Dark Theme:
![](https://files.slack.com/files-tmb/T0K0M84G5-F0X1RHU7L-ddc9b81590/tabcenter2_1024.png)

**Comment by phlsa** [comment]
Asked Stephen to take a look at this.

**Comment by johngruen** [comment]
Closing, we'll focus on fixing nits.
