### ISSUE TITLE
Predictive functionality plans? Like old moz labs experment

### ISSUE THREAD

**Issue by Noitidart** [bwinton/VerticalTabs#161]
Hi I was wondering if the team considered predictive functionality? Right now it shows the last sites visited in the history section, this is kind of useless.

I found this moz labs experiment was really good until it broke - https://addons.mozilla.org/en-US/firefox/addon/prospector-predictive-newtab/

**Comment by chuckharmston** [comment]
@Noitidart great feedback! We do indeed have a team experimenting with some smarter client-side predictive...stuff. It's unclear what form that it will take yet, but it's rather exciting.

I'd imagine that this gets closed as out of scope for tab center (I'll let @bwinton make that call), but CCing @telliott @twobraids to make sure that this feedback gets noticed nonetheless.

**Comment by Noitidart** [comment]
Oh very cool! No prob thanks I understand the close. I'm super eager to see a predictive stuff. Kind of in sync with the bot stuff lately haha

**Comment by johngruen** [comment]
Closing as out of scope right now. Letting team mates on activity stream know to check this idea out.
