### ISSUE TITLE
Cmd + Click/Open in new tab missing feedback

### ISSUE THREAD

**Issue by confuser** [bwinton/VerticalTabs#163]
When on the last tab in the list, opening a new tab via Cmd + Click on a link (or right clicking a link and selecting open in new tab), the tab list doesn't scroll to show the just opened tab.

The lack of feedback makes it unclear as to whether or not the tab was actually opened and only becomes apparent when switching to the next tab, or manually hovering over the tab list and scrolling

**Comment by ericawright** [comment]
fixed with #153 tab list now scrolls
