### ISSUE TITLE
Tree structure?

### ISSUE THREAD

**Issue by bpierre** [bwinton/VerticalTabs#165]
It would be great to have a tree structure.

**Comment by saithis** [comment]
I would rather have tab groups, that are collapsible. The currently available tab group addons don't have a sidebar functionallity.

For a tree structure there is [Tree Style Tab](https://addons.mozilla.org/de/firefox/addon/tree-style-tab/).

**Comment by bpierre** [comment]
Or Tab Tree, which is the one I am using at the moment: https://addons.mozilla.org/en-US/firefox/addon/tab-tree/

@saithis I am not sure I understand the difference between collapsible tab groups and a tree structure, could you describe it?

**Comment by bwinton** [comment]
A hierarchical tree structure is out of scope for this add-on.  But I totally recommend Tree Style Tab or Tab Tree if that's what you're looking for!  😃

We might think about some sort of tab grouping feature in a later version of this, but I'm not sure what form it will take at this point.

Thanks for the feedback!

**Comment by saithis** [comment]
@bpierre For me tab grouping works like this:
```
pinned tab 1
pinned tab 2
group 1
   tab 1
   tab 2
group 2
   tab 3
```
Groups are not tabs themselfes.

An tab trees like this:
```
tab 1
tab 2
   tab 2.1
      tab 2.1.1
      tab 2.1.2
   tab 2.2
tab 3
   tab 3.1
```
There every tab can have child tabs

**Comment by bpierre** [comment]
@saithis Ah it makes sense now, thanks for explaining!
