### ISSUE TITLE
Close/Maximize buttons position distored while using HTitle addon 

### ISSUE THREAD

**Issue by bull500** [bwinton/VerticalTabs#166]
The close/maximize buttons apear on Tab Center instead of the right corner of the HTitle addon in maximized mode

**Comment by johngruen** [comment]
@bull500 not sure what you mean. Can you add a screenshot or two?

**Comment by bull500** [comment]
@johngruen here :)
The addon seems to abandoned, but its the only way for Linux GNOME users to actually get rid of the big fat Title Bar. Its on github as well. 
Plus the native Firefox title bar bug looks like it will take quite sometime to arrive due to GTK stuff.

![screenshot from 2016-05-12 02-26-15](https://cloud.githubusercontent.com/assets/8917275/15196317/572449b6-17e9-11e6-991a-b1d4c2f3ac2a.png)

**Comment by wresuolc** [comment]
This will be addressed in #234 for some definition of addressed

**Comment by terrycloth** [comment]
One dubious workaround is to uncheck "Show window controls" in HTitle's options. This *removes the window controls* obviously, so it's not a perfect solution, but this does declutter the top of the Tab Center side bar. And you can still exit Firefox from the main menu button, and switch to other applications by clicking your graphical shell's window list / task bar / dock / overview. And the keyboard shortcuts to close or minimize the window remain intact.
