### ISSUE TITLE
Close button positioned far too right and small clickable area

### ISSUE THREAD

**Issue by bull500** [bwinton/VerticalTabs#167]
Windows gets a nice clickable close button and its positioned properly there. 
Here its hard to click it on Linux
Firefox 49

![screenshot from 2016-05-11 16-08-16](https://cloud.githubusercontent.com/assets/8917275/15178341/979eda1c-1792-11e6-8365-27a34f0a2b33.png)

**Comment by rhky** [comment]
For me, having to wait for the X to appear and then moving the cursor before clicking feels like a time obstacle. What if clicking the favicon closed the page? Or hovering over the favicon superimposed the X to click?

**Comment by tobia** [comment]
@rhky You don't really have to wait. On Mac and Windows the close button is big and appears instantly when hover the spot. The usability is brilliant. I think this is just a bug in the Linux version.

Mac & Windows:

![mac](https://cloud.githubusercontent.com/assets/48756/16239875/3b275082-37e7-11e6-95a9-c4b95f07f51a.png)

Linux:

![linux](https://cloud.githubusercontent.com/assets/48756/16239876/3feaf204-37e7-11e6-98ca-f15f4d6529ee.png)
