### ISSUE TITLE
Opening FF's Customize view when using Tab Center hides all FF UI

### ISSUE THREAD

**Issue by riyad** [bwinton/VerticalTabs#168]
When trying to "Customize" FF while using Tab Center the customize UI will cover all of the UI except the title bar. So customizing anything but the menu hanger is not possible.

Clicking "Exit Customize" will
* not close the customize UI but leave it open rendering FF unusable. The only possibility to recover is to restart FF. (This happened once after installing Test Pilot + Tab Center, but I couldn't reproduce it after the restart)
* now it returns to the tab *after* the one that was open before entering "Customize"

**Comment by johngruen** [comment]
@romanblanco adds the following: 
I have no option to align items in the main menu with Tab Center feature enabled:
See the screenshots:  *(sorry for the resolution)*

Disabled:
![b](https://cloud.githubusercontent.com/assets/1187051/15182306/1537ed3a-178c-11e6-9243-1bb33d62cb4f.png)
Enabled:
![c](https://cloud.githubusercontent.com/assets/1187051/15182322/205590b4-178c-11e6-976a-bc4c522b481e.png)

**Comment by johngruen** [comment]
#108? Possible mitigation to bring back main toolbar on top?

**Comment by ericawright** [comment]
related:
When clicking on "restore defaults" and then "Exit Customize" the titlebar disappears.

![screen shot 2016-05-17 at 1 08 33 pm](https://cloud.githubusercontent.com/assets/10803178/15331832/23c2cc7c-1c31-11e6-8091-6ae8d0f98e6c.png)

**Comment by ugggf** [comment]
It is still a problem in Firefox 46 on Linux Mint 17.3 Cinnamon 64bit.

**Comment by rtanglao** [comment]
also reported in twitter: https://twitter.com/_jfen/status/736389420958556160 ( i added this link so i can report back to @_jfen if need be)

...Roland "currently taking care of @fxtestpilot on twitter" Tanglao
