### ISSUE TITLE
Get rid of scroll bar in testpilot tab center

### ISSUE THREAD

**Issue by johngruen** [bwinton/VerticalTabs#169]
This comes from a bug filed on test pilot:

Scroll bar appears on the tab center when I hover mouse cursor over it (all my tabs fit well in the Firefox window).
Platform: Windows8.
The scroll bar doesn't appear on Ubuntu.

![firefox-tabcenter-scroll](https://cloud.githubusercontent.com/assets/457958/15177865/02c2af20-177b-11e6-9b26-3c4502725979.png)

**Comment by johngruen** [comment]
@g7r ^

**Comment by johngruen** [comment]
@bwinton tasking  you with repro'ing

**Comment by alex-mayorga** [comment]
¡Hola!

FWIW I can reproduce this rather easily by just enabling "Tab Center" on Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0 ID:20160523030225 CSet: 16663eb3dcfa759f25b5e27b101bc79270c156f2

Please see below.

Do let me know if there's anything you need.

This is on Win7 with "Windows Classic" theme.

¡Gracias!
![tabcenter-issue-169](https://cloud.githubusercontent.com/assets/649262/15478527/7c64c8f4-20e0-11e6-8f8b-f263ae193739.png)

**Comment by Zaggy1024** [comment]
Hm, I didn't realize that it was meant not to have a scroll bar, but for windows with a large number of tabs (like mine) it's very nice to have the scroll bar on.

**Comment by alex-mayorga** [comment]
¡Hola!

The scroll bar shall appear when needed and be hidden when it is not needed IMHO.

¡Gracias!

**Comment by macxcool** [comment]
I can verify the unnecessary scroll-bar present in Windows 8.1 64-bit but not on ArchLinux 64-bit.
It's a problem when you're moving quickly because you aim your mouse at the minimized tab and then the scroll bar appears and the click does nothing.
