### ISSUE TITLE
Tab Center should not add its sidebar to popups that can't actually have tabs

### ISSUE THREAD

**Issue by dholbert** [bwinton/VerticalTabs#176]
STR:
 1. With "Tab Center" installed, visit https://login.persona.org/ and click "Sign In".
 2. Look at the popup that appears.

ACTUAL RESULTS:
The popup has a Tab Center sidebar.

EXPECTED RESULTS:
The popup should not have a Tab Center sidebar.  (It's just UI cruft; this is a strictly single-tab popup, with no user-exposed way to open a new tab.  So, Tab Center serves no purpose in this popup. Just as we hide the tabstrip for this popup in normal Firefox, we should also hide Tab Center.

**Comment by dholbert** [comment]
This is even worse if you've "pinned" Tab Center in its open position, in your main browser-window.

In that case, it's also "pinned" in the popup (and makes the popup a good bit wider).

**Comment by dholbert** [comment]
Screenshots (first with Tab Center collapsed, then with it pinned):
![Screenshot of popup with collapsed tab center](https://cloud.githubusercontent.com/assets/426803/15189261/96f8d5d8-175e-11e6-8a05-b7e1ab18cf46.png)
![Screenshot of popup with pinned tab center](https://cloud.githubusercontent.com/assets/426803/15189287/a45856ae-175e-11e6-9893-98cf804c45c9.png)

**Comment by Riscky** [comment]
It's not very useful to see the tab center in windows with only one tab either. The plus button must be visible in that case though

**Comment by johngruen** [comment]
This is  a dupe, closing in favor of #135
