### ISSUE TITLE
Current tab is not scrolled in viewport if tab sidebar is pinned

### ISSUE THREAD

**Issue by jniederm** [bwinton/VerticalTabs#178]
Steps to reproduce:
1. Enable Tab Center
2. Open enough tabs to make vertical scrollbar to show
3. Pin the side bar
4. Select first tab (on the top)
5. Press 'New ...' button to open new tab

Result:
New tab is opened, activated and put at the bottom of side bar. However sidebar is not scrolled down thus selected tab (highlighted with bold text) is not visible in sidebar.

Expected result:
Side bar should should refocus always re-scroll for selected tab to be visible after tab operations like:

* open new
* close
* tab switch

as it does while unpinned.

**Comment by wresuolc** [comment]
Does this still happen in the latest version?  This should be fixed.  Thanks!
