### ISSUE TITLE
Bottom of web content is clipped when Bookmarks Toolbar is enabled

### ISSUE THREAD

**Issue by bgrins** [bwinton/VerticalTabs#184]
STR:
Open `data:text/html,<style>div {position:fixed; bottom: 0; left: 0; right: 0; background: lightblue; }</style><div>hi</div>`
Enable Bookmarks Toolbar

Expected:
The light blue element at the bottom of the page is visible

Actual:
The light blue element slides under the browser chrome and cannot be scrolled to.

I noticed this originally on a Google Docs spreadsheet where the 'sheets' section at the bottom of the UI was clipped.

**Comment by bwinton** [comment]
Another dupe of #105…  :)
