### ISSUE TITLE
Bookmark sidebar does not display

### ISSUE THREAD

**Issue by depaloan** [bwinton/VerticalTabs#187]
When TabCenter 1.16 is enabled I am unable to display the Bookmarks Sidebar: clicking on "View Bookmarks Sidebar" or pressing CTRL+B do not nothing. Firefox ESR 45.1.0

**Comment by SonRiab** [comment]
See #62 :)

**Comment by bwinton** [comment]
Yeah, dupe of #62.  Thanks!
