### ISSUE TITLE
An option to hide title bar.

### ISSUE THREAD

**Issue by Nidre** [bwinton/VerticalTabs#188]
In it's current state the app doesn't actually save much space since the Windows Title Bar(Top window frame) is left visible.

**Comment by daiheitan** [comment]
Also on Mac, this addon forces to show the system titlebar, which is kinda ugly when combining with the awesomebar.

**Comment by bwinton** [comment]
Done on purpose in #87, because hiding the titlebar and not showing tabs breaks OS X.

**Comment by Nidre** [comment]
@bwinton 

Well, it could work quite well on Windows. And honestly it would look a lot better and would actually save a lot more space.

This is the sole reason I've disabled this addon/experiment.

+ With the addition of right hand version, OS X could also work.

**Comment by leewalsh** [comment]
I was afraid of something like that, @bwinton.

On OS X, the same problem appears to happen with the tabs on top, but it appears to have been solved by placing a blank space to the left of the first tab where the stoplights can fit. Could something similar be considered for the vertical tabs?

I like @Nidre's idea of putting the tabs on the right, too. But there you'd run into the scroll bar, which may be harder to avoid.

**Comment by bwinton** [comment]
Yeah, tabs on the right is issue #7.  We'll probably get around to it sometime, but it's also got some tricky edge cases…  :)

**Comment by daiheitan** [comment]
I come up with an idea that maybe the `+` and `new tab` button could align to right ( with the pin button ), this gives the buttons the space they needed. What do you guys think ? @bwinton

**Comment by Dimas-sc** [comment]
I think it should be considered this option, the title bar is ugly and uselss

**Comment by bwinton** [comment]
@Dimas-sc: You're free to have your opinions, but don't assume they hold for everyone, and your language in this comment in particular was over the line.  If you can't be constructive and polite, please find a different project to "help" with.

**Comment by Dimas-sc** [comment]
I never wanted to offend anyone, I'm sorry if you misunderstood me. You've censured it so now we don't know if really it was 'over the line' or you had a bad day. Hope you could abstract of this supposed bad language and you got the idea after it.

**Comment by bwinton** [comment]
You're not being judged on your intention or what you want, but on what you typed.  I have a copy of it in my email, and as the person responsible for this project I can tell you it absolutely crosses the line.  (And I'm having a great day, thanks!  🙂)

**Comment by goldenbr0wn** [comment]
Do you think there is a way to circumvent #87 ? Saving vertical space (especially on laptops) is one of the main features of this extension and the presence of the title bar make it useless in this regard.

**Comment by bwinton** [comment]
Possibly, but this extension is going to stop working in about 6 weeks, so I don't think it would be worth spending the time on it. For the WebExtension version, it will hopefully be [fixed in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447) instead of having every add-on try to hack around it.

(As a side note: Please don't comment in that bug unless you have specific technical knowledge that isn't already there. There are already far too many comments there that just say "I want this too!" which doesn't help it get fixed. 😉 Thanks!)
