### ISSUE TITLE
When bookmark toolbar is enabled, tab list should be aligned with it 

### ISSUE THREAD

**Issue by Flore-mozfr** [bwinton/VerticalTabs#190]
I still have the bookmark toolbar enabled and the list of the tabs starts above it and it looks not so neat
![capture d ecran 2016-05-12 a 16 21 19](https://cloud.githubusercontent.com/assets/6987429/15217911/e46a5ae4-185d-11e6-923f-895e37285fd4.png)
The addon should detect where the content of the page really starts and align itself with it. It would look better. People could use other toolbars.

**Comment by wresuolc** [comment]
We don't have plans to expand the button on top since a person could have unlimited toolbars and just keep pushing their tabs down the page.  Thanks for your feedback though.
