### ISSUE TITLE
New Tab button label truncated in french

### ISSUE THREAD

**Issue by Boboseb** [bwinton/VerticalTabs#191]
The "New Tab" button label is truncated in french l10n :
![capture d ecran 2016-05-12 a 16 22 54](https://cloud.githubusercontent.com/assets/4552841/15217986/2e43ab2a-185e-11e6-806b-f334760e35f2.png)

**Comment by bwinton** [comment]
I believe we recently fixed this in #160 (which hasn't been released yet).  Thanks!
