### ISSUE TITLE
Make Tab Center auto-collapse

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#2]
One of the main issues we've seen in testing was that people always had issues with the size of tab center. When it was wide, there were complaints about taking space away from the website. When it was narrow, it became hard to distinguish tabs and even harder to close them.

We can address all of those issues by auto-collapsing and expanding the tab sidebar.

Interactive mockup: http://phlsa.github.io/fx-tab-center-2/
Code: https://github.com/phlsa/fx-tab-center-2

**Important details**
- When expanding, tab center overlays the viewport (it doesn't change the width of the viewport)
- There is a delay of 300ms (value up for debate) for both expanding and narrowing
- When the user moves the cursor over the leftmost pixel of the window, the expansion happens instantaneously. That way, in full screen mode we take advantage of fitts law.

**Comment by bwinton** [comment]
More specs:
* Will we let the user expand/contract the sidebar or make it fixed-width? - Fixed at 5% of the viewport for now.
* How far out to expand? - Fixed at something slightly larger than default width of a tab.
* It should be possible to close a tab.  - The button should be quite wide and at the end of the tab.

**Comment by phlsa** [comment]
Updates:
- Close button added
- 260px seems to be a good expanded width

**Comment by bwinton** [comment]
I think I'm going to close this, and we can file followup bugs for anything else we find.
