### ISSUE TITLE
Facebook chat improperly displayed 

### ISSUE THREAD

**Issue by xbouroseu** [bwinton/VerticalTabs#203]
The Facebookt chat is not displayed properly. When the add-on is enabled it hides some part from the typing area. Same happens with the Friends list.

Screenshot:

![screenshot_04 03 43_13-05-2016](https://cloud.githubusercontent.com/assets/1462165/15234993/45c77418-18c0-11e6-804a-ec84c53a6004.png)

Mac OS X El Capitan
Latest Firefox 46.0.1 Release channel.

**Comment by bwinton** [comment]
Dupe of #105.
