### ISSUE TITLE
Side Bar navigation and effects

### ISSUE THREAD

**Issue by eranshul20** [bwinton/VerticalTabs#206]
Below are the issues in side bar categories 

1. Side bar transition from Pin-it button is not smooth, it get stuck many times. Doesn't respond.
2. Closing new tabs on slide bar , closing button UI for Red cross not generate for new tab on hover mouse after closing one tab.
3.  No loader appear on web pages or on side bar website tabs to showcase processing to user.
4. On mouse over> Sliding and closing back of side bar is not smooth.

Firefox 46.0.1
Machine OS: Windows 10, 64 bit

**Comment by wresuolc** [comment]
Duping to #208 for general speed
