### ISSUE TITLE
Login on Web App using social app login is not letting pop-up box/message to get authenticate

### ISSUE THREAD

**Issue by eranshul20** [bwinton/VerticalTabs#207]
1. Use login for a web app> Login via FB> new pop-up window open up to fetch FB permissions and credentials to connect> User not able to Login. Blocker.

Firefox 46.0.1
Windows 10, 64 bit 
![login via fb in tab view firefox test pilot prog 13 may 16](https://cloud.githubusercontent.com/assets/12758815/15239919/bc3b762e-1903-11e6-84ed-b498c97d9572.png)

**Comment by ericawright** [comment]
possible dupe of #135

**Comment by bwinton** [comment]
Well, I think we would need more data about why the user wasn't able to log in…
