### ISSUE TITLE
FF 45.0.2 on Linux - Tabcenter stuck forever trying to enable

### ISSUE THREAD

**Issue by sdholden** [bwinton/VerticalTabs#215]
CentOS 6.4 and FF 45.0.2
STream and search working OK, as far as i can tell, but tabcenter is stuck trying to enable...darn.

**Comment by bwinton** [comment]
Is there anything in the Browser Console (available from Ctrl-Shift-J, I believe)?

**Comment by ericawright** [comment]
perhaps related to https://github.com/mozilla/testpilot/issues/802 ?

**Comment by bwinton** [comment]
Yeah, I think so.  Closing this one as a dupe of that.  🙂
