### ISSUE TITLE
Double scroll bars

### ISSUE THREAD

**Issue by danhash** [bwinton/VerticalTabs#216]
The vertical tab bar has two scroll bars

**Screenshots**
![double scrollbar 2](https://cloud.githubusercontent.com/assets/16405573/15257880/83a62580-1916-11e6-93a1-6bdc87b928eb.png)
![double scrollbar](https://cloud.githubusercontent.com/assets/16405573/15257879/837f374a-1916-11e6-988e-4f1587cbc42f.png)

**Comment by F1ynn** [comment]
I have this issue on Win7 although not on Win10. Very annoying as it causes all tabs to jump if you activate the tab on top.

**Comment by ugggf** [comment]
It also happens in Linux when using some Firefox themes (like FT DeepDark).

**Comment by bwinton** [comment]
Dupe of #169.  (Well, this describes two, but we'll want to get rid of one.  :wink:)
