### ISSUE TITLE
New tabs appear at the bottom first and only then jump to the top

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#22]

**Comment by bwinton** [comment]
Similarly, if you hold down ctrl-t, you'll get some tabs at the bottom, and others at the top.
I will claim that the current behaviour is good enough for the prototype, though, and that it would be tricky to make it work correctly.

**Comment by bwinton** [comment]
So, I solved the first problem, but I don't think I can solve the second in this prototype, because we (currently) need to wait for the page to load before finding out whether it's `about:newtab` (and thus we want to move it to the top) or not (and thus we don't).
