### ISSUE TITLE
Incompatibility with Hide Caption Titlebar Plus

### ISSUE THREAD

**Issue by User-47186985** [bwinton/VerticalTabs#220]
I use [this add-on](https://addons.mozilla.org/de/firefox/addon/hide-caption-titlebar-plus-sma/?src=ss) to simply hide the title bar, but Tab Center seems to force the Windows title bar to appear. Also, it messes up the interface if I enable/disable HCTP.

**Comment by wresuolc** [comment]
Dupe to #234
