### ISSUE TITLE
Tab Centre stopped working after using Dev tools

### ISSUE THREAD

**Issue by meandavejustice** [bwinton/VerticalTabs#229]
_Opening on behalf of @Hazz223 from https://github.com/mozilla/testpilot/issues/847_
>Hi,

>Found when using the dev tools on Facebook (turns out they have a nice little console output to stop people >getting hacked, who knew?) that when i closed them suddenly the tab centre stopped working.

>I activated and deactivated, which didn't work. But closing and re-opening Firefox did the trick.

>Using the standard build for Firefox (46.0.1), on Mac.

>Like the test pilot program though. Nice friendly way to try out new features!!!

>Cheers,
>Harry

**Comment by wresuolc** [comment]
None of us have been able to reproduce this.  We think this is related to an update and was just a coincidence.  Can you still reproduce it?

**Comment by Hazz223** [comment]
I've tried to reproduce it, and had no luck. Thanks for looking into this. Very odd. Thanks though!!

**Comment by ericawright** [comment]
In that case, dupe of #226
