### ISSUE TITLE
Allow resizing the side bar when pinned

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#23]

**Comment by carl-di-ortus** [comment]
And while at it - check this label near new tab that should really say "New Tab" when it fits.
![vertical-tabs](https://cloud.githubusercontent.com/assets/1598063/15161134/a60482b0-1705-11e6-91b0-96a6741b3313.png)

**Comment by rubenerd** [comment]
The only reason I'm not using this on my MacBook Air. A draggable border to adjust size would be consistent with how sidebars work in other applications.
