### ISSUE TITLE
Not sure what to do...

### ISSUE THREAD

**Issue by willygee** [bwinton/VerticalTabs#232]
Vertical tabs have reverted to regular horizontal position. Using Windows 10 and FF 46.0.1
Should I reinstall? If so, how?

**Comment by bwinton** [comment]
Just restart Firefox, and it should be fine, but before you do!!!
Could you please launch the Browser Console (Ctrl-Shift-J should pop it up), and let me know if there's anything there that looks like an error?  Thanks!

**Comment by wresuolc** [comment]
Duplicate of #226

**Comment by willygee** [comment]
Worked perfectly, thanks!
