### ISSUE TITLE
[Suggestion] Ability to customize CSS

### ISSUE THREAD

**Issue by Yonezpt** [bwinton/VerticalTabs#233]
I am not aware if we can do this here in this issue tracker, but seeing how many have already touched the subject for specific cases I would like to suggest an option that allows all of those to be included.

Provide the ability to customize Vertical Tabs. Currently I was able to customize it through Stylishg (weirdly enough), but that only lasted until the browser restarted so I assume the add-on styling is on a racing condition and because of that certain custom styles are never applied.

This is not an urgent request, but if the feature is targeted for release it would be great if it could be customized seeing that the rest of the browser UI is also customizable. This, of course, is meaningless if Vertical Tabs is meant to be shipped as a part of the browser UI, in that case this suggestion pointless.

**Comment by wresuolc** [comment]
Duping this to #189

**Comment by Yonezpt** [comment]
Thanks for the dupe, couldn't find it through search.
