### ISSUE TITLE
Let's add an incompatibility section to the readme

### ISSUE THREAD

**Issue by wresuolc** [bwinton/VerticalTabs#234]
We're incompatible with a bunch of add-ons, let's document that somewhere.

**Comment by johngruen** [comment]
@wresuolc @bwinton i think we can do this just in the django admin for tab center.

**Comment by alex-mayorga** [comment]
¡Hola!

https://addons.mozilla.org/en-US/firefox/addon/yahoomailhideadpanel/ breaks a bit as one needs to scroll horizontally.

¡Gracias!

**Comment by wresuolc** [comment]
Also TooManyTabs from https://github.com/mozilla/testpilot/issues/976

**Comment by ericawright** [comment]
+ OmniSidebar re:#389

**Comment by ericawright** [comment]
+ New Add-on Bar re: #368
