### ISSUE TITLE
tab center appears even when tabs should be hidden in window

### ISSUE THREAD

**Issue by mystor** [bwinton/VerticalTabs#235]
There appears to be no new-tab button in this context, and the tabs pane is empty. The pin button is present and appears to work correctly.

<img width="851" alt="screen shot 2016-05-16 at 4 29 55 pm" src="https://cloud.githubusercontent.com/assets/1261662/15302969/95561d98-1b83-11e6-987c-7965a21e511d.png">

I would think that the desired behavior would be for the tab center to not be present in this situation.

**Comment by bwinton** [comment]
Dupe of #135, I believe…
