### ISSUE TITLE
Toolbar not visible when in customize view with tab center enabled

### ISSUE THREAD

**Issue by mystor** [bwinton/VerticalTabs#236]
It appears as though it is covered by the Customize... window's graphics.

<img width="1438" alt="screen shot 2016-05-16 at 6 32 18 pm" src="https://cloud.githubusercontent.com/assets/1261662/15305951/94016252-1b94-11e6-9ed0-ddd538ab89ec.png">

**Comment by bwinton** [comment]
Dupe of #168.
