### ISSUE TITLE
Tabs in the bottom not visible after opening multiple tabs

### ISSUE THREAD

**Issue by xbouroseu** [bwinton/VerticalTabs#238]
After opening a multitude of tabs (in my case more than 25) then suddenly the bottom-"last" tab is not fully accessible through the scroll-bar in the Tab-Center. If there are even more tabs opened then this is not limited only to the "last' tab but also some of the previous ones.

Here is an example where the "last" tab is not clearly visible even though the scroll-bar has fully reached the bottom:
![screenshot_14 37 45_17-05-2016](https://cloud.githubusercontent.com/assets/1462165/15321587/1ebf1820-1c40-11e6-8fa3-64c65f39a0bb.png)

And here it is visible after i maximize the window (but when i open more tabs then they don't appear as well):
![screenshot_14 39 03_17-05-2016](https://cloud.githubusercontent.com/assets/1462165/15321593/2f84ce20-1c40-11e6-945b-84ece90cd68c.png)

Firefox latest release-channel 46.0.1

**Comment by johngruen** [comment]
I'm seeing this one as well: 

<img width="1477" alt="screen shot 2016-05-17 at 4 07 52 pm" src="https://cloud.githubusercontent.com/assets/3323249/15325106/9474e2bc-1c49-11e6-8903-8f0af9a216a4.png">

**Comment by ericawright** [comment]
I'm seeing this on Firefox Dev edition 48, but not on Firefox 46

**Comment by NormG1** [comment]
I just opened an issue on the exact same bug. I am on Firefox 46 on a Mac.

**Comment by neonhacker** [comment]
I have the same issue ... can't scroll down to the last tab on the list. This occurs in full screen mode or not. Mac pro laptop, Firefox 46.0.1
