### ISSUE TITLE
Multiple New-Tabs placed on top instead of bottom when multiple tabs are open

### ISSUE THREAD

**Issue by xbouroseu** [bwinton/VerticalTabs#239]
If i have opened multiple tabs (in my case more than 25) then it try to create multiple new tabs at once. 
They start appearing in the bottom of the Tab-Center but after a second **some of them** automatically move to the top.

Example (i know this doesn't help much):
![screenshot_14 53 35_17-05-2016](https://cloud.githubusercontent.com/assets/1462165/15321666/9652e6be-1c40-11e6-99e2-1b0620433dec.png)

**Comment by bwinton** [comment]
Yeah, in the current architecture we need to wait for the tab to load before being able to figure out whether it's a "new tab" or a link opened in a new tab.  They should _all_ move to the top, but that's being tracked in #3.
