### ISSUE TITLE
Back to top no matter what

### ISSUE THREAD

**Issue by mobird53** [bwinton/VerticalTabs#240]
Windows 10
Fire Fox ![screenshot_20160517083521](https://cloud.githubusercontent.com/assets/19408706/15322405/a6493996-1c0a-11e6-9b71-2580742d1227.png)

Tabs used to work great loved them. But when I shut my computer off for the weekend, this being my wok computer, the tabs are back to the top. Nothing I do will get them back to the side. I've tried enabling and disabling it multiple times. Nothing seems to work.
One other thing to note, I use a skin the LFG skin. (LFG= Looking For Group, an online web-comic)

**Comment by ericawright** [comment]
@mobird53 this is probably due to an update. If you restart Firefox, Tab Center should be restored.

**Comment by wresuolc** [comment]
closing in favor of #226. thanks for filing
