### ISSUE TITLE
middle-click closes tabs

### ISSUE THREAD

**Issue by rillian** [bwinton/VerticalTabs#244]
Middle-clicking on tabs closes them. Even if they're pinned.

Waiting for the window to unroll and then clicking the close box feels like it takes forever so this is really convenient to discover. (In practice I switch to the tab and use ctrl+w.) On the other hand, I use middle-click on links to open new tabs all the time, and the way I discovered this was by clicking on my pinned twitter tab to open a copy so I could look something up. So deleting my pinned tab (and losing its state!) was not what I expected at all, and feels inconsistent.

Reproduced on Firefox Nightly with a fresh profile on Linux (x86_64 Fedora 24).

**Comment by wresuolc** [comment]
If I middle-click a tab on Linux w/ Firefox Release it closes the tab (without Tab Center installed).  I think this is normal functionality.  Are you using a different add-on?

**Comment by bwinton** [comment]
Closing due to lack of response, and because it sounds like the default behaviour…

**Comment by passcod** [comment]
A different from top tabs style is that there's no visual difference and no reduced click target (which is something that was mentioned as being a reason for allowing middle-click-closing on pinned tabs in Firefox, see [Bugzilla 1345576](https://bugzilla.mozilla.org/show_bug.cgi?id=1345576#c1).) for pinned tabs when in the "drawer closed" state.

That makes it much easier to accidentally middle-click a pinned tab, and it's something I've been burned with quite a few times.
