### ISSUE TITLE
Why no used similar design of gitlab?

### ISSUE THREAD

**Issue by ripper2hl** [bwinton/VerticalTabs#247]
![captura](https://cloud.githubusercontent.com/assets/2611201/15339354/acf2b648-1c49-11e6-8df2-97f939a68b01.PNG)

Atlassian use similar bar for jira :smiley: 

[Gitlab](https://about.gitlab.com/features/)

**Comment by bwinton** [comment]
I'ld like to claim it's because we're trying to do different things, but mostly it's because we didn't find those when designing it.  😉
