### ISSUE TITLE
Cannot scroll fully without maximizing window to full screen

### ISSUE THREAD

**Issue by NormG1** [bwinton/VerticalTabs#248]
I love Vertical Tabs, but there is a bug.
I have a long list of Open Tabs.
I am using a MacBook Pro running OSX v10.11.4
If the window is not maximized, I cannot scroll down the list of tabs. There are always a few at the bottom that are simply not accessible.
The workaround is to maximize the window. Run Firefox full screen. The menu bar goes away unless I move the cursor up there. The dock is simply not accessible in this full screen mode.
BUT, I now can scroll the full list of tabs in Vertical Tabs.
It has all the makings of a bug. One I wish someone would fix. Don't look at me. I am just an end user and I don't write code. Sorry.

**Comment by NormG1** [comment]
This issue duplicates issue #238

**Comment by bwinton** [comment]
Resolved duplicate.
