### ISSUE TITLE
After disabling Tab Center and closed all windows, the tab of a former closed window remains (and reduced size)

### ISSUE THREAD

**Issue by my-le** [bwinton/VerticalTabs#249]
After having disabled Tab Center and closed all windows, and then open a new window: 
– the tab of a former closed window remains
– and it has a weird reduced size
I had to quit and relaunch FF.

<img width="404" alt="tabcenter" src="https://cloud.githubusercontent.com/assets/10426601/15341666/625ac890-1c90-11e6-9db5-6cd406acd531.png">

**Comment by johngruen** [comment]
@my-le it's possible that you've ''pinned' the tab, which is something you can do in tab center, but also in normal Firefox. Is the small tab still there? if you ctrl+click on the little tab, you can confirm that it's pinned by looking for the 'Unpin tab' item in the context menu (see attached) image. Clicking that should make the tab big again. 
<img width="175" alt="screen_shot_2016-05-18_at_9_11_28_pm" src="https://cloud.githubusercontent.com/assets/3323249/15371765/60c3bdb8-1d3d-11e6-8ba9-b60496d6e6f3.png">

Let us know if that's helpful!

**Comment by ericawright** [comment]
Closing due to lack of response (and looks like a pinned tab).
