### ISSUE TITLE
Contextual identities not visible within vertical tabs

### ISSUE THREAD

**Issue by jonathanKingston** [bwinton/VerticalTabs#256]
When I have vertical tabs enable and also containers also enabled I should still be able to see what container I am in for all non selected tabs.

Perhaps all tabs should glow on the left as they do vertically now.

Something like:
![selection_179](https://cloud.githubusercontent.com/assets/338988/15403729/4c3cf4d0-1df2-11e6-861f-63ef1b6b7e6c.png)

**Comment by bwinton** [comment]
So, this seems like a very niche feature, and while I would probably accept a pull-request that did something, I don't think we'll be working on it any time soon.  Thanks!

**Comment by jonathanKingston** [comment]
Hey Blake,

To clarify I am working on containers at the moment and I left this as a
placeholder for myself. Thanks for reminding me!

I will see if I can get this in before the work week if that is possible.

Thanks

**Comment by bwinton** [comment]
It still seems pretty niche, and we still don't have a good design for it.  As I said above, we would probably accept a pull-request that implemented something, but I don't want contributors to spend time working on it over something that has more wide-reaching value.
