### ISSUE TITLE
LastPass screen does not render when Tab Center enable

### ISSUE THREAD

**Issue by AutomatedTester** [bwinton/VerticalTabs#265]
# STR:

1. Install LastPass ( I have 4.1.7a installed (which I think is the e10s one))
* Make sure there is at least 1 item in lastpass
* Click the last pass icon in the browser chrome
* Click on Preferences

# Expected Results
Shows the preferences pane

# Actual Results
The Tab Centre tab bar is visible but the rest of the window doesnt render.

**Comment by EMLVIRUS** [comment]
I could not reproduce this bug actually with your steps.
Have you tried to reinstall LastPass?

**Comment by AutomatedTester** [comment]
![fullscreen_5_25_16__11_14_am](https://cloud.githubusercontent.com/assets/128518/15536613/f86e0fd4-2269-11e6-912f-8e7e74c89d2c.jpg)

I have. All I get is the screenshot above. If I disable tabcenter then it works perfectly.

**Comment by EMLVIRUS** [comment]
@AutomatedTester I noticed you are on Mac OS but I'm on Windows, which is supporting the feature perfectly. So it should be system compatibility.

**Comment by escapewindow** [comment]
I'm also hitting this problem on OSX nightly.

**Comment by ericawright** [comment]
@AutomatedTester can you verify this once more?  I was unable to duplicate it, and there was an update pushed end of last week that may have affected it.

**Comment by escapewindow** [comment]
This is now working for me.

**Comment by AutomatedTester** [comment]
Yup, this is working great now! Closing the bug
