### ISSUE TITLE
Text is unreadable when using a dark theme

### ISSUE THREAD

**Issue by aplocher** [bwinton/VerticalTabs#270]
I believe the vertical tabs are using the themes text color for all tabs, but only the background color for the selected tab.  I could be wrong...

![2016-05-23_13h52_05](https://cloud.githubusercontent.com/assets/1132447/15484182/92e4dc56-20ed-11e6-8e82-5d93ef469cb1.png)

**Comment by Screwtapello** [comment]
I believe this is a dupe of #132 (going by the various other tickets closed as dupes of that bug), fixed a few days ago but not yet released.

**Comment by aplocher** [comment]
Thank you, I believe you're correct.  I quickly skimmed the list before posting this but didn't notice that one.  Thank you.  I'll close this for now
