### ISSUE TITLE
Windows 7 glitchy graphics

### ISSUE THREAD

**Issue by wresuolc** [bwinton/VerticalTabs#271]
Originally from https://github.com/mozilla/testpilot/issues/870

When tab center is active, and you click on a bookmark in your bookmarks bar, this causes some glitchy graphics. (Windows 7, fairly old computer, newest version of Firefox, I think)

[UPDATE]: New discovery about this issue, this only happens when I go to inbox.google.com (Google Inbox) via the bookmarks bar. This could be on the google side of this, but I can't tell.

screenshot: https://cloud.githubusercontent.com/assets/12704804/15367065/2bde031c-1cdc-11e6-8e4b-ef0591fbe596.PNG

**Comment by bwinton** [comment]
So, I checked into this, and it's a problem with inbox.google.com not conforming to a small screen…
(https://mobile.twitter.com/ works just fine.)  Thanks for the report!

**Comment by wresuolc** [comment]
Also related: https://bugzilla.mozilla.org/show_bug.cgi?id=560305
