### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by Qhuea** [bwinton/VerticalTabs#274]
Even though I only have 2 tabs open in tab center, a scroll bar appears. 
![capture](https://cloud.githubusercontent.com/assets/12704804/15507425/6b7b2a7e-2180-11e6-8074-38602b1eb68e.PNG)

**Comment by rodude123** [comment]
It doesn't happen for me when I have more than 2 tabs I normally have about 10 or 12 and it doesn't do that. I don't how many tabs that I would need for a scroll bar Here Is what I have right now.
![tab centre right now](https://cloud.githubusercontent.com/assets/10896262/15513201/9b534bc2-21db-11e6-95e0-41d860eda0c0.png)

**Comment by bwinton** [comment]
Dupe of #169.  Thanks!
