### ISSUE TITLE
How do bug reporters know when the fix ships in Test Pilot?

### ISSUE THREAD

**Issue by hwine** [bwinton/VerticalTabs#277]
Granted, maybe not a TC issue, but it would be good to know when we should retest to verify fixes. Can there be a milestone or something set up so folks can get notified?

E.g. my issue #267 got closed as a dupe of #132, which was already closed with "fix landed but not released".

How will I know it is time to verify?

**Comment by bwinton** [comment]
It's a reasonable question.  It'll likely be mentioned in [the release notes](https://github.com/bwinton/VerticalTabs/releases/latest), which are linked off of the experiments page (in a really tiny font).  In general, we're aiming for bi-weekly releases, so if something says it's fixed, you should wait a couple of weeks and re-test.

(We used to use milestones, but dropped them for some reason…  @clouserw might have more details…)

**Comment by hwine** [comment]
Thanks - one followup on something not clear in the test pilot program:
What do I have to do to get the new release?
* fully automatic update? (any notification?)
* manually update test pilot as a normal addon?
* something else?

**Comment by bwinton** [comment]
Should be fully automatic, no notification, like a normal add-on…

**Comment by bwinton** [comment]
@hwine Time to verify.  (You may need to re-start the browser after update.  Changes to XUL sometimes get ignored…)
