### ISSUE TITLE
Clicking on a tab moves it to the top

### ISSUE THREAD

**Issue by andymckay** [bwinton/VerticalTabs#285]
... when the list of tabs is greater than the height causing a scroll bar and the tab you pick is in the top section of tabs, it makes that top the bottom of the page. It annoys me because I lose the context of the tab and the tabs around it.

Here's a video, notice when I click the github tab 5 seconds ago.

https://www.dropbox.com/s/7bcq9tyifp1l9is/tab-centre-jumping.mov?dl=0

**Comment by bwinton** [comment]
Fixed by #245, but not released yet.  Thanks!
