### ISSUE TITLE
All opened tabs are closed after dragging any tab

### ISSUE THREAD

**Issue by LadyQA** [bwinton/VerticalTabs#289]
Steps:
1. Go to Tab center
2. Add several new tabs
3. Drag any of the tabs to the main screen of the current page

Actual: All opened tabs are closed. Dragged tab is left  in Tab center
http://screencast.com/t/a9xOPXuCllN

**Comment by Keith94** [comment]
That's because the tab you're dragging actually gets moved to a new window. It's normal behavior.

**Comment by bwinton** [comment]
Resolved, working as designed.  Thanks!
