### ISSUE TITLE
Fix style and alignment issues on Windows 7

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#29]
<img width="730" alt="screen_shot_2016-04-05_at_17_55_05" src="https://cloud.githubusercontent.com/assets/514315/14288706/35a6a43a-fb58-11e5-8fbc-2420e2ae8b14.png">

**Comment by bwinton** [comment]
Latest code looks like this:
<img width="861" alt="screenshot 2016-04-06 15 26 56" src="https://cloud.githubusercontent.com/assets/159571/14329968/1f353f18-fc0c-11e5-929f-5023231e217d.png">

Anything I'm missing?  Anything else you want me to do while I'm here
