### ISSUE TITLE
One more tab is created after dragging it up to hover over "New Tab" button

### ISSUE THREAD

**Issue by LadyQA** [bwinton/VerticalTabs#290]
Steps:
1. Go to Tab center
2. Add several new tabs
3. Grab any tab and drag it up to hover over "New Tab" button

Actual: One more the same tab is created 
http://screencast.com/t/nCyKsDLY

**Comment by bwinton** [comment]
Ah, yes, it's the unexpected duplicate-tab feature!
Resolved working as designed.  🙂
