### ISSUE TITLE
Problem with Persona / extension

### ISSUE THREAD

**Issue by blue101** [bwinton/VerticalTabs#292]
I have the problem here https://www.camp-firefox.de/forum/viewtopic.php?f=7&t=117952
described

**Comment by bwinton** [comment]
For those of us who don't speak German, could you describe the problem in English here?  Thanks!

**Comment by blue101** [comment]
Sorry my english is not so good I-but try it to describe the problem
When I go to Vertical Tabs breaks me the Persona I.deacttivate  me the add-on
Hide Caption Titlebar Plus everything works again

**Comment by bwinton** [comment]
That's a good description, thanks!  Can you post a couple of screenshots, too?
One with everything enabled and broken, and another with Tab Center disabled?

**Comment by blue101** [comment]
Hello
I have here 2 Screen made hope it's good and everything is ersichtlich.Bei two Vertical Tabs enabled.
In 1.ohne Hide Caption title bar Plus and 2 .with the Erweiterung..Wie I said, though I have this extension works on inactive Vertical Tabs
![ashampoo_snap_2016 05 26_15h55m03s_001_](https://cloud.githubusercontent.com/assets/19579970/15577499/1a7ea018-235d-11e6-8202-4bb01f2d3fbb.png)
![ashampoo_snap_2016 05 26_16h00m57s_002_](https://cloud.githubusercontent.com/assets/19579970/15577511/1f7c056a-235d-11e6-8894-a98ba4766372.png)

**Comment by bwinton** [comment]
Will be fixed (kind of) by #234.
