### ISSUE TITLE
[Suggestion] Group related tabs together in a tree (like Tree Style Tab extension)

### ISSUE THREAD

**Issue by rcmero** [bwinton/VerticalTabs#295]
First of all, I am fond of how this extension works, great job on it.

As the title explains, the Tree Style tab extension has provided vertical tabs on Firefox for several years now, and it also has the function to group tabs together in a tree, related to the tab that opened it. ([This page](http://www.howtogeek.com/207887/how-to-use-vertical-tree-style-tabs-in-your-web-browser/) explains how it works.) It would be nice if Tab Center were to implement this as well.

**Comment by bwinton** [comment]
While I quite like the tree functionality of Tree-Style Tabs, this add-on is designed for a simpler use-case, so we won't be adding that.  Thanks for the suggestion, though!

**Comment by rcmero** [comment]
Okay, I understand. Thanks for the quick reply.
