### ISSUE TITLE
Empty tab list is displayed on pop-ups

### ISSUE THREAD

**Issue by rcmero** [bwinton/VerticalTabs#297]
![captura de tela 2016-05-26 22 29 09](https://cloud.githubusercontent.com/assets/5708421/15590884/e12e202e-2391-11e6-8aff-b9b0881890dc.png)
Not sure if anyone reported this yet. Since you can't add a tab this seems unnecessary.

**Comment by bwinton** [comment]
Dupe of #135, which should be fixed as of a couple of minutes ago.  :wink:  Thanks!
