### ISSUE TITLE
Add CHANGELOG file

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#298]
Diffs are possible, but not necessarily easy. We can use [v1.17...v1.18](https://github.com/bwinton/VerticalTabs/compare/v1.17...v1.18) to compare 2 releases to each other, but it isn't a list we can easily scroll and see what is new in each specific release.

We use [**conventional-changelog-cli**](https://github.com/conventional-changelog/conventional-changelog-cli) on some projects, but there are probably a few other options too.

Currently on https://testpilot.firefox.com/experiments/tab-center we use a changelog of https://github.com/bwinton/VerticalTabs/releases/latest, which takes the user to a page like this:

![release_everything_on_the_side _ _bwinton_verticaltabs_ _github](https://cloud.githubusercontent.com/assets/557895/15592695/a43606fa-235a-11e6-8bcc-db8226694550.png)

**Comment by wresuolc** [comment]
We just triaged this and were thinking that https://github.com/bwinton/VerticalTabs/releases was a pretty good changelog.  If we just linked to that in the README does that cover this issue?
