### ISSUE TITLE
unsafe CPOW usage at verticaltabs.jsm:130

### ISSUE THREAD

**Issue by alex-mayorga** [bwinton/VerticalTabs#300]
¡Hola!

Upon enabling "Tab Center" I see this into the "Browser Console":

unsafe CPOW usage verticaltabs.jsm:130

Filing this FWIW.

¡Gracias!
Alex

**Comment by bwinton** [comment]
Dupe of #99, but thank you for the more-up-to-date line number!

(And, actually, if you could test with 1.19, and let me know what the new line number is if you see it again, I would appreciate it.  😀)
