### ISSUE TITLE
'Customize' pane doesn't show top toolbar

### ISSUE THREAD

**Issue by osunick** [bwinton/VerticalTabs#303]
Also, on my system (46.0.1, Win64) the sync pane in the customize view says I'm logged out when I am not.

**Comment by folz** [comment]
Possible duplicate of #302? (Looks like we noticed it at about the same time.)

**Comment by bwinton** [comment]
This looks like a duplicate of #168, which should be fixed in the latest version.  (The sync pane saying you're logged out also happens without Tab Center, and looks like it's being [tracked in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1214801).)

Thanks for the report!
