### ISSUE TITLE
Tabs opened by ctrl-clicking could also open at the top (like new tabs).

### ISSUE THREAD

**Issue by djmylt** [bwinton/VerticalTabs#309]
If I open a new tab by pressing Ctrl+T, then the new tab opens above my current tabs. But if I open a link in a new tab it opens below my current tab. I can't speak for others, but I would personally prefer it if all the new tabs opened in the same direction.

**Comment by bwinton** [comment]
So, we originally had new tabs opening at the bottom, but user testing revealed that people didn't know where they were showing up, and so we changed it to open them below the New Tab button as much as possible.  Given that, we're probably not going to fix this (unless we get more data indicating that the new position doesn't work), but thank you for the issue report!

**Comment by nielsdg** [comment]
I don't really get the point. Doesn't the following statement
> we changed it to open them below the New Tab button as much as possible.

conflict with this one?
> Given that, we're probably not going to fix this (unless we get more data indicating that the new position doesn't work)

What I mean is that opening a new tab from a link is not consistent in direction (below the current tab), _especially_ with the new position. So shouldn't _all_ tabs be opened at the top to be consequent? That's at least where I'd expect them as a user.

**Comment by bwinton** [comment]
It is consistent, if you think about opening a new tab as opening it from the New Tab button (which is where people's attention was focussed when clicking the button).  We _could_ have opening a new tab with ctrl-t open in a different location than opening it with the button, but that seems even more inconsistent than the current behaviour…

Finally, if users are having problems with a feature, then it doesn't really matter how consistent it is, it's still broken, and needs fixing.

**Comment by nielsdg** [comment]
I think we're having a misunderstanding? :stuck_out_tongue: 

I _really like_ the new tabs opening at the top as it means newer tabs stay on top, while older (less important?) tabs get pushed to the bottom. However, (I think) it should *also* open a new tab from a link at the top, which it doesn't right now.

**Comment by bwinton** [comment]
Ah, yeah, I thought you meant the opposite…  I see what you're asking for now, and it's an intriguing concept.  I'm not sure how well it would work if you were far down in the tab list, and we had to scroll to show the newly-opened tab, but it does seem like something worth investigating…

**Comment by nielsdg** [comment]
Indeed, that might be an issue. Maybe at least open tabs above the current tab when ctrl-clicking then, to be consistent with the direction?

**Comment by Screwtapello** [comment]
Tabs opened by clicking a link in another application also appear at the bottom of the list; they should appear in the same place as everything else.

I wouldn't want Ctrl-clicked tabs to always open at the top of the list; I find it convenient to have them grouped next to the tab that spawned them. But I guess if they were *above* rather than *below* (and if Ctrl-W focussed the next tab above), that would be close enough.

**Comment by djmylt** [comment]
Sorry for not responding sooner, this issue picked up a discussion after I went to sleep.

> I'm not sure how well it would work if you were far down in the tab list, and we had to scroll to show the newly-opened tab, but it does seem like something worth investigating…

The way I think opening a link in a new tab works in normal Firefox is that the link opens one tab to the right of the current tab. Might it be worth doing something similar here, where opening a link in a new tab opens it one tab above the current tab?

**Comment by wresuolc** [comment]
We'll address this in #322
