### ISSUE TITLE
Something in the last build broke the instant opening when pointing at the leftmost pixel

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#31]
Running 1.9

**Comment by bwinton** [comment]
Which OS?  (Still on Windows 7?)

**Comment by phlsa** [comment]
Definitely on Windows 10, haven't checked on Windows 7.
I thought it might be due to Nightly, but it's also happening in release.

**Comment by johngruen** [comment]
This seems to be working again @phlsa if you are not in a bunker could you pull down the latest and give it a shot

**Comment by bwinton** [comment]
I can't replicate it on the latest version on Windows 10 or OS X, so I'm going to resolve it fixed.
