### ISSUE TITLE
'Close tabs below?'

### ISSUE THREAD

**Issue by djmylt** [bwinton/VerticalTabs#310]
I found the 'Close Tabs to the Right' option to be confusing when I first tried out this extension as it wasn't clear which direction it was referring to. Given how this closes all the tabs below the current tab, would it make more sense to relabel it as something like 'Close Tabs Below'?

**Comment by bwinton** [comment]
Whoops, this was fixed by 289c96603c71ec52c05d5aa28e4858170fdb57a9, but that said that it fixed #312 instead…
