### ISSUE TITLE
Position of pinned tabs and new tabes

### ISSUE THREAD

**Issue by abdulmoeedammar** [bwinton/VerticalTabs#312]
I like the idea of opening the new tabs at the top, but with pinned tabs that doesn't work that well.

I think it might be a good idea to have pinned tabs at the bottom (preferably in separate section and un-scrollable, but that's another story).

I also see other reported issues/feedbacks regarding the position of newly opened tabs in different scenarios (e.g. "Open Link in New Tab", opening link from another application etc.). 

We can avoid most of the confusion if we equate right/left of the normal horizontal tabs to above/below here. So what was previously at right side (new tab button, opening link in new tab) should be above, and what was previously at left side (pinned tabs) should be at the bottom.

This will also give a proper solution for issue #310 by giving option to close "Close tabs above"

**Comment by wresuolc** [comment]
We'll address this in #322
