### ISSUE TITLE
Tabs opening at top confusing with alt+# hotkeys to switch tabs

### ISSUE THREAD

**Issue by bradmont** [bwinton/VerticalTabs#315]
The switch to new tabs opening at the top is terribly confusing to me. I tend to keep my most important tabs at the top (or on the left with horizontal tabs). This way, I can get to them quickly with alt+[1-8], without having to think about what is where. Having new tabs pop up in the first position breaks this functionality, as I no longer know where my tabs are -- they should remain in the same position they were in when I created or explicitly moved them.

I don't find pinning tabs is a sufficient solution to this though, as currently "important" tabs are often also transient, so not worth pinning: for example, a five minute text chat. Furthermore, there is no keyboard shortcut to pin/unpin a tab, making it a non-starter for keyboard-based tab navigation. Perhaps include an option to put new tabs on the bottom?

**Comment by jasontibbitts** [comment]
Personally I find it extremely confusing even without using those hotkeys.  I, too, kept my important tabs on the left which with the new extension became the top.  In addition, when I'm browsing I often open various new links, which naturally open down the list.  Then if I open a fresh tab, it opens way up at the top of the list which is quite bizarre.  And, finally, when Firefox is called to open a new URL (usually via Ctrl-click in a terminal window) it opens a tab at the bottom of the list.

**Comment by wresuolc** [comment]
We'll address this in #322
