### ISSUE TITLE
launching devTools windows makes UI unusable

### ISSUE THREAD

**Issue by edmoz** [bwinton/VerticalTabs#32]
1. (i'm on mac) goto a page
2. ctrl+click > select inspect element

actual: devtools window doesn't appear and view area is shifted so that the bottom of pages cannot be scrolled.

expected devtools should appear, and page should scroll as normal.

**Comment by pdehaan** [comment]
Also, if you have devtools tab open and then install the Tab Center addon (via TestPilot or whatever), your devtools disappear.

**Comment by pdehaan** [comment]
Still able to reproduce w/ v1.9.

**Comment by bwinton** [comment]
I _think_ this is a P1…

**Comment by bwinton** [comment]
Ta-da!
<img width="940" alt="screenshot 2016-04-14 11 27 13" src="https://cloud.githubusercontent.com/assets/159571/14533696/1a8024dc-0234-11e6-80f9-4e9054ff3a51.png">
