### ISSUE TITLE
Odd looking Telemetry pings

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#327]
**DISCLAIMER:** I have no idea what I'm talking about, but I'm just looking at the shape of the ping versus the document in [docs/metrics.md](https://github.com/bwinton/VerticalTabs/blob/c343baac3e0d02d19dfd0aecf82501bd90a0dd03/docs/metrics.md#data-collection-details) [versus what the Universal Search telemetry payload looks like].

### Steps to reproduce:
1. Install Tab Center via Test Pilot.
2. Do some stuff to generate some Telemetry ping data.
3. Go to about:telemetry and wait for some telemetry ping data for "testpilottest" to appear. (I find I need to switch to "Archived ping data) and look for pings ending with " - testpilottest".)

### Actual results:

```json
{
  "version": 1,
  "test": "tabcentertest1@mozilla.com",
  "payload": {
    "test": "tabcentertest1@mozilla.com",
    "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0",
    "version": 1,
    "payload": {
      "tabs_created": 5,
      "tabs_destroyed": 1,
      "tabs_pinned": 0,
      "tabs_unpinned": 0,
      "tab_center_pinned": 3,
      "tab_center_unpinned": 1,
      "tab_center_expanded": 13
    }
  }
}
```

That looks scary to me, and oddly redundant and overly nested. From my very ignorant understanding (and the docs) it seems like we could kill the top level `version`, `test`, and just send the top `payload` object as our payload to telemetry.

Here's what the [docs/metrics.md](https://github.com/bwinton/VerticalTabs/blob/c343baac3e0d02d19dfd0aecf82501bd90a0dd03/docs/metrics.md#data-collection-details).

```js
{
 "test": "tabcentertest1@mozilla.com",  // The em:id field from the add-on
 "agent": "User Agent String",
 "version": 1,  // Just in case we need to drastically change the format later
 "payload": {
    “tabs_created”: 1000,
    “tabs_destroyed”: 1000,
    “tabs_pinned”: 5,
    “tabs_unpinned”: 4,
    “tab_center_pinned”: 1,
    “tab_center_unpinned”: 0,
    “tab_center_expanded”: 9999
    /* “tab_center_teased”: 1234  (Version 2) */
  }
}
```

---

For giggles sake, here's what a sample Universal Search ping looks like:

```json
{
  "version": 1,
  "test": "universal-search@mozilla.com",
  "payload": {
    "didNavigate": true,
    "interactionType": "key",
    "recommendationShown": false,
    "recommendationSelected": false,
    "selectedIndex": -1
  }
}
```

![telemetry_data](https://cloud.githubusercontent.com/assets/557895/15764055/c17570e8-28dc-11e6-8cda-b7bc19a12522.png)

**Comment by pdehaan** [comment]
Continuing my trend of idiotic and uninformed questions, would it make sense to pass along the add-on version in the ping data?

**Comment by bwinton** [comment]
It could, although it would be in the telemetry data regardless…
