### ISSUE TITLE
Add metrics for things we're interested in!

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#33]

**Comment by ckprice** [comment]
Here is the [WIP metrics document](https://docs.google.com/document/d/1GbNUslE25J1TWURBxU3lZstaebwTKu3LgMXgJoPiPSg/edit#heading=h.yjgaxo9r79r1).

**Comment by johngruen** [comment]
@bwinton here's a draft Metrics doc for you, I'm out today, but going to ask @clouserw for a sanity check. If there's too much here, let's talk about paring it down: 

 https://gist.github.com/johngruen/34ced8ad051f964d72b60756ac9adadd

**Comment by bwinton** [comment]
Fixed by 3326b6cc6888326fb03ed7e02ef6d6c41414042f
