### ISSUE TITLE
"New Tab" bar still broken

### ISSUE THREAD

**Issue by User-47186985** [bwinton/VerticalTabs#335]
I put a button in the title bar like described on #301 . In this version it just disappears. I suggest putting it in a bar below the tabs instead.
The pin button is still invisible (probably because of dark theme) ~~and now I can't even hit it because the tab sidebar keeps retracting and expanding.~~ NVM, the last was a conflict with HCTP.

**Comment by ericawright** [comment]
Currently  they are just hidden, that is on purpose. We need to discuss still on where to put them - but a bar on the bottom could be a good idea.
