### ISSUE TITLE
Can't see the find menu with tab center

### ISSUE THREAD

**Issue by johngruen** [bwinton/VerticalTabs#34]
CMND + F to find something and there's no visible find search box... maybe related to the dev tools thing? 

If I start typing after hitting CMND + F results will highlight, so the form is there, but it's just not visible.

**Comment by edmoz** [comment]
I think the bottom 30px are not show in the viewing window... my gmail no longer displays yellow calendar alerts

**Comment by bwinton** [comment]
Ta-da!
<img width="940" alt="screenshot 2016-04-14 11 27 13" src="https://cloud.githubusercontent.com/assets/159571/14533696/1a8024dc-0234-11e6-80f9-4e9054ff3a51.png">

@edmoz Can you let me know if gmail's calendar alerts work for you now?  (Also, afaik we're only targeting Release.  Getting it working under more advanced versions of Firefox is a new bug…)

**Comment by johngruen** [comment]
@bwinton 😍
