### ISSUE TITLE
Home Page is different after turning on Tab Center

### ISSUE THREAD

**Issue by Facyber** [bwinton/VerticalTabs#343]
I am using Add-On "Speed Dial" and I set it as my default Home Page, so every time I open new tab, Speed Dial page will show up instead default one, but after I turn on Tab Center, I get the regular new tab page, Search Bar on the top and recommended pages under it. 

Is there a way to fix this?

**Comment by ericawright** [comment]
It seems that if you restart Firefox your speed dial settings should be restored, and work with Tab Center.

**Comment by Facyber** [comment]
Yes it is okay now, didn't even thought about that. I apologize.

**Comment by ericawright** [comment]
not a problem, thanks for reporting!
