### ISSUE TITLE
New Tab Button Dissapears Randomly

### ISSUE THREAD

**Issue by Thelolguy1** [bwinton/VerticalTabs#344]
Linux Mint17.3

The tab center's new tab button seems to dissapear randomly.

**Comment by ericawright** [comment]
It is possible to remove it by right-clicking. Could that be what happened by any chance? Otherwise, have you noticed any patterns in when it shows and when it disappears, or percentage of when it's gone?

**Comment by Thelolguy1** [comment]
It seemed to have reappeared when I switched back to the old tabs, but
disappeared soon enough. In the case that I did remove the New Tab button,
how do I re-enable it?

**Comment by ericawright** [comment]
you can click the browser menu button in the right, then go to customize. Then drag the tab icon back into place. (it's easier to do this with TC disabled)

**Comment by Thelolguy1** [comment]
Oh, thanks, I'll try it tonight.
