### ISSUE TITLE
Add icon and description to about:addons page

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#35]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14509569/c972d434-0181-11e6-9786-468ed20dac08.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14509580/d8358a20-0181-11e6-9104-6cf119322450.png)

Not sure if we want to add our custom Tab svg icon so we have something better than the default puzzle piece icon in about:addons.

As for the description, maybe something as simple as the GitHub repo's "Firefox add-on for arranging tabs vertically." text.

**Comment by pdehaan** [comment]
I attempted a PR for this, but it turns out that the off-white tab icon from TestPilot is a bad match for near-white about:addons page. May need to summon @johngruen's art skills for a more official icon we can use/steal.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14514039/d6e5d948-01a1-11e6-90a2-a33bddfcc820.png)

**Comment by pdehaan** [comment]
We have a new icon! We'll just need a darker variant for use in about:addons,

![firefox_test_pilot_-_experiments](https://cloud.githubusercontent.com/assets/557895/14871599/9f91900c-0c98-11e6-8238-1e2115a323b7.png)

**Comment by bwinton** [comment]
How's this?
<img width="358" alt="screenshot 2016-04-28 14 07 29" src="https://cloud.githubusercontent.com/assets/159571/14896209/999a37dc-0d4a-11e6-8324-c7867ce53370.png">
<img width="822" alt="screenshot 2016-04-28 14 08 10" src="https://cloud.githubusercontent.com/assets/159571/14896221/a8da545c-0d4a-11e6-8791-2b05aae6a1e9.png">
