### ISSUE TITLE
Conflict with multiselect add-on

### ISSUE THREAD

**Issue by Keith94** [bwinton/VerticalTabs#350]
[Bug 566510 - Allow multiselect operations on tabs :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/bug-566510/)

With Tab Center and the above add-on installed, tabs can no longer be deselected with left mouse click. With Tab Center disabled it works as expected.

**Comment by ericawright** [comment]
Thank you, will add it to the list of #234

**Comment by Keith94** [comment]
Well the add-on mostly works except for that one "feature" I described.. Isn't there a chance of looking into it and fixing it?

**Comment by ericawright** [comment]
There may be down the road, but other issues are larger priorities at the moment. So, for now we are just collecting a list of add-ons that are conflicting.
