### ISSUE TITLE
Sidebars are hidden behind tabs when pinned open

### ISSUE THREAD

**Issue by sevaan** [bwinton/VerticalTabs#36]
Pinned my tabs open an then opened my bookmarks sidebar. I think it's hidden behind my tabs. Maybe force the sidebars to the right-side of the browser?

**Comment by johngruen** [comment]
@bwinton can confirm. in this screenshot showing the lightweight theme bug, you can see a toolbar behind TabCenter:

![screen shot 2016-04-18 at 11 43 33 am](https://cloud.githubusercontent.com/assets/3323249/14610216/f213beda-055a-11e6-96ff-be03f9d00585.png)

**Comment by pdehaan** [comment]
I'm seeing some odd using the default Firefox theme in Beta and pinning my tab as well (in v1.10):

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14649660/e5f24154-061c-11e6-8c50-4b4368cfae25.png)

Note that the tabs are pinned to the left, but I have an odd empty zone on the RIGHT side of browser, and all my page contents are underflowing the pinned sidebar. Unpinning seems to work as expected.

**Comment by johngruen** [comment]
closing this in favor of #62
