### ISSUE TITLE
Downloads button in tab bar is hidden irreversibly.

### ISSUE THREAD

**Issue by Zaggy1024** [bwinton/VerticalTabs#365]
Without Tab Center installed, I have my downloads button to the right of the tab bar like this:

![firefox_2016-06-16_20-26-49](https://cloud.githubusercontent.com/assets/3149592/16138192/b13a64f2-3400-11e6-98fe-77baaf95fb1a.png)

In previous versions of Tab Center, the downloads button would appear in the top bar of the sidebar to the left of the sidebar pinning button, but it has now disappeared. This makes it so that without disabling the extension, I'm completely unable to move the downloads button.

**Comment by Keith94** [comment]
Yeah, the extension developers made the buttons hidden by default (see: fae84ecb)

You can show it again by overriding the css if you want. Just add it with [Stylish](https://addons.mozilla.org/firefox/addon/stylish/) :)

```css
#TabsToolbar > toolbarbutton,
#TabsToolbar > toolbaritem {
  display: block;
}
```
![snag 2016 06 17 00 39 44](https://cloud.githubusercontent.com/assets/5490615/16143818/1a2d936c-3424-11e6-8bfa-01cab56e1af1.png)

**Comment by Zaggy1024** [comment]
I just hope that the removal of the buttons doesn't mean they're planning on forcibly removing the buttons when the addon is activated instead of allowing that area to be customized.

**Comment by bwinton** [comment]
We don't have any plans to allow that area to be customized, because it's so small already.
(And based on that, I'm resolving this wontfix.  But we will do something better than just hiding the buttons in a future update.  Probably moving them to the toolbar…)

Thanks for your report!

**Comment by Zaggy1024** [comment]
Seems to me it can fit about as much as any reasonable person would want to put to the right of the tab bar with horizontal tabs...

**Comment by bwinton** [comment]
Yep, but it doesn't show up in Customize Mode, and it's not hooked in to the customization code, so even if it did show up, dragging things to and from it would cause really strange effects, and given the [other things we hope to put there](https://mozilla.invisionapp.com/share/GT22ZN6QW#/screens), it doesn't make a lot of sense to put a lot of work into making (and keeping) that part customizable.

**Comment by Zaggy1024** [comment]
Ah, good point, I do forget that this isn't the final design of the UI.

**Comment by lindhe** [comment]
I _really_ think you should make a better effort of not breaking stuff like this. I should not have too do research to find how I can access downloaded files. Viewing downloaded files is somewhat an important feature (for example if you were to ever download a file and wanted to open it easily).
