### ISSUE TITLE
+ button is missing "new tab" text and possibly other translations missing?

### ISSUE THREAD

**Issue by tobia** [bwinton/VerticalTabs#375]
I just noticed on a German OS that the [ + New Tab] button is missing the label:

![windows](https://cloud.githubusercontent.com/assets/48756/16240015/d862a036-37e7-11e6-8f54-978bd324727c.png)

I'm not sure if this is a bug with the addon or if it's something funny with this particular OS installation.
But the rest of Firefox shows a lovely German interface, including the "Neuer Tab" translation where appropriate (see the actual tab in the screenshot.)

**Comment by armenzg** [comment]
I believe this is a duplicate of https://github.com/bwinton/VerticalTabs/issues/353

@tobia I would like to duplicate this issue with #353, however, you also mention that there might be some translations missing. However, from looking at the screenshot it is unclear for me to know that there are missing translations.

Do you mind if we close this issue and open a new issue specifically focused on the missing translations with screenshots that help us see those missing translations?

Thanks for your help!

**Comment by bwinton** [comment]
So, all the translations should be missing, since version 1 was only being released in en_US.  When we get to a later run of Tab Center (and Test Pilot as a whole), then we'll look into internationalizing and localizing the code…  (I think we should leave this open to find out why the text isn't there, but seeing German text there would surprise me greatly.)

**Comment by tobia** [comment]
My bad. I compared two environments with more than one difference between them: Mac OS X in English vs. Windows in German. I wrongly concluded that the missing label was due to the language difference, while #353 clearly shows that it's due to the OS difference.

I'll go ahead and close this issue.
