### ISSUE TITLE
Cannot display tabs on the right when using the Light theme

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#38]
Found in 1.9

### Steps to reproduce:
1. Install the add-on via Test Pilot.
2. Go to about:addons and check the "Display tabs on the right" checkenboxen.
3. Toggle between the 3 different themes.

### Actual results:
I cannot seem to display the tabs on the right of the browser if I'm using the "Light" theme.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14510100/92d1a7b8-0184-11e6-9a16-53254267736a.png)
**Figure 1:** "Light" theme, but always stuck on left side of the screen.

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14510119/a86e3366-0184-11e6-8cb7-bdcfd90f8c99.png)
**Figure 2:** "Dark" theme, correctly docked to right side of the screen.

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14510142/c579b7aa-0184-11e6-8a33-2292eea0c814.png)
**Figure 3:** "Default" theme, correctly docked to the right side of the screen.

**Comment by bwinton** [comment]
I think we're going to remove themes, so anything that depends on those will be "fixed" by that.  :wink:
