### ISSUE TITLE
Misleading repository description

### ISSUE THREAD

**Issue by tobia** [bwinton/VerticalTabs#380]
I hope this is not considered "nitpicking," but I think the project description (the short text shown on the [project homepage](https://github.com/bwinton/VerticalTabs) under the main tab bar) is a bit misleading. It points to a Mozilla Addon page for the original extension this was forked from.

This could mislead new users who somehow end up here. A better link would be the one shown in the Readme: https://testpilot.firefox.com/experiments/tab-center

**Comment by bwinton** [comment]
Oh, yeah, fixed.  Thanks!
