### ISSUE TITLE
Strange border on right of verticaltabs-box

### ISSUE THREAD

**Issue by Nolski** [bwinton/VerticalTabs#382]
Running FF49 on OSX I notice a strange white border on the side of `<vbox id="verticaltabs-box">` I'm not sure if it's intended but it has a small `1px` white border on the right side. I think this stems from line 69 in `light.css`. 

It'd be nice to just remove the border but I wanted to make an issue and check before I submit a patch.

actual:
<img width="90" alt="screen shot 2016-06-24 at 9 11 30 pm" src="https://cloud.githubusercontent.com/assets/2600677/16353931/bc346248-3a51-11e6-9db7-3be4120d77b8.png">

proposed:
<img width="93" alt="screen shot 2016-06-24 at 9 21 36 pm" src="https://cloud.githubusercontent.com/assets/2600677/16353937/efac8e52-3a51-11e6-9fe3-7617ac9c8129.png">

**Comment by dbarjs** [comment]
I think the same, but a dark border is better!

**Comment by bwinton** [comment]
Well, we've changed the colours, but we're keeping the border to distinguish the side bar from similarly coloured pages.
