### ISSUE TITLE
Collapsed sidebar covers left of page

### ISSUE THREAD

**Issue by Digivonity** [bwinton/VerticalTabs#389]
Webpages without left margin are harder to read. The collapsed tab bar remains around 50px wide. I can imagine that it should be between the window border and the page border but then that's not working on Ubuntu 16.04. Neither when I collapse Ubuntu's taskbar which is also at the left hand. If it's intended to work like this, then please consider a feature to optionally collapse Vertical Tabs to a few pixels.

**Comment by bwinton** [comment]
Hmm, it shouldn't do that…  Can you send a screenshot, and try it again with your other add-ons disabled (just in case it's a compatibility issue)?  Thanks!

**Comment by Digivonity** [comment]
I skipped the screenshot and went straight for the add-ons. It turns out that the issue occurs because of the OmniSidebar add-on. I'm not sure if you're familiar with it. After changing it's placement from right to left window, Tab Center stopped overflowing page content. It would still be nice if you can fix it, so that both OmniSidebar and Tab Center can both be used by hovering the window edges, but for the time being it's ok to use a shortcut key for OmniSidebr instead.

**Comment by Digivonity** [comment]
Too bad. This morning the issue occurred again and could only be solved by disabling OmniSidebar.
