### ISSUE TITLE
Tab bar visible with fullscreen videos

### ISSUE THREAD

**Issue by Keith94** [bwinton/VerticalTabs#392]
I installed the latest patch "Make the pinned sidebar resizable" 230dc32

Now when the tabs are pinned and I set a youtube video to fullscreen mode, the tab sidebar is still visible with a blank background.

![snag 2016 06 30 15 18 40](https://cloud.githubusercontent.com/assets/5490615/16506444/3cfd0fe0-3ed7-11e6-9366-58c8d7610a93.png)

**Comment by bwinton** [comment]
Ooh!  Good catch!  I'll fix this before we release it…
