### ISSUE TITLE
New tabs open in the wrong place

### ISSUE THREAD

**Issue by chris-morgan** [bwinton/VerticalTabs#395]
In stock Firefox, <kbd>Ctrl+T</kbd> creates new tabs at the end of the tab bar.

With this extension, it’s creating the new tabs at the start, after any pinned tabs.

**Comment by Croydon** [comment]
AFAIK this is on purpose, but I'm not absolutely sure.

**Comment by Croydon** [comment]
#373

**Comment by ericawright** [comment]
this is on purpose, though soon you will be able to set a preference to open at the top or the bottom of the list re: #373
