### ISSUE TITLE
Tabbar overlaps content when pinned open.

### ISSUE THREAD

**Issue by Celti** [bwinton/VerticalTabs#398]
This just started happening with the latest addon update today.

[Here](https://celti.name/esoterica/tabcenter-collapsed.png) is the collapsed view (all normal).
[Here](https://celti.name/esoterica/tabcenter-pinned.png) is the pinned view (overlapping the left side of the page).

**Comment by bwinton** [comment]
Hmm, weird.  Can you tell me which add-ons you have installed, and which operating system you're using?

**Comment by Celti** [comment]
Arch Linux on x86_64, freshly updated, with Firefox Developer Edition 49.0a2.

Extensions:
Activity Stream	1.1.0
DNSSEC/TLSA Validator	2.2.0.2.1-signed.1-signed
Firefox Hello	1.4.2
Greasemonkey	3.8
Herp Derp for YouTube™	1.4.2
HTTP/2 and SPDY indicator	2.3
Live HTTP headers	0.17.1-signed.1-signed
Multi-process staged rollout	1.0
Pocket	1.0.3b1
Reddit Enhancement Suite	4.6.1
Send Tab to Device	0.7.1-signed.1-signed
Session Manager	0.8.1.12
Simplified Tab Groups	0.4.0
SixOrNot	2.0.0.1-signed
Tab Center	1.21
Test Pilot	0.6.5-tag-2016-06-09
uBlock Origin	1.7.6
uMatrix	0.9.3.6
Wallabag	2.0.0
Web Compat	1.0

**Comment by Celti** [comment]
Aaaaaugh, looks like Simplified Tab Groups is to blame. ><

I really can't live without *some* sort of tab grouping... time to start digging.

**Comment by bwinton** [comment]
I've been using https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/ but you might prefer https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

(Also, you reminded me that I broke full-screen mode, so I just fixed that… :wink:)

**Comment by Celti** [comment]
Aha! I'm wrong, no other addon is to blame — instead, it looks like the resizing feature breaks unless you restart the browser after updating. Everything I listed above enabled, browser restarted, and problem is gone — maybe this update needs to be flagged as "requires restart"?

**Comment by bwinton** [comment]
Argh, yeah.  I don't think we have a good way to flag that, but that's something we're looking into.  Thanks for the report!
