### ISSUE TITLE
Pin button invisible when not selected

### ISSUE THREAD

**Issue by devanes** [bwinton/VerticalTabs#399]
I don't know whether I happened because I did something wrong, or due to an update, but I had the tab bars in both my windows pinned and they suddenly where unpinned. Which was a bit annoying. But then I noticed the I couldn't see the pin button anymore. I could still click on in and once active, it was visible, but when it's not active, the button is not visible.

**Comment by seiferflo** [comment]
Confirmed for me as well

**Comment by ericawright** [comment]
@devanes @seiferflo there was an update, so it is likely related. If that's the case try restarting Firefox and please send a screenshot if it continues :)

**Comment by devanes** [comment]
I already did a restart, as the tab bar also covered part of the menu and tool bars. It fixed that problem, but the button was still invisible. I can send screenshot, but basically with the pin button not selected the bar with "New Tab" in it (where the pin button should be on the right) is just grey over the full width of the tab bar. There's no indication at all that there should be a button or similar.

**Comment by devanes** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6104616/16619583/01bdb940-438f-11e6-8ebf-c02c9fb86835.png)

**Comment by ericawright** [comment]
fixed with #1eba711
