### ISSUE TITLE
Tab Center controls overlap with zoom controls

### ISSUE THREAD

**Issue by ameliaabreu** [bwinton/VerticalTabs#4]
<img width="596" alt="screen shot 2016-03-15 at 9 27 51 am" src="https://cloud.githubusercontent.com/assets/2185387/13785379/933569ac-ea90-11e5-8878-7e09977cdf84.png">

**Comment by phlsa** [comment]
@ameliaabreu Could you elaborate on what the issues of the participant were? From the screen shot it looks like the zoom controls are visible and accessible, but just in a different place. Were they unable to locate the controls or was there a different issue?

**Comment by johngruen** [comment]
Trying to repro on a win machine. My fond hope is that this is obsolete
