### ISSUE TITLE
Close button doesn't extend the full height

### ISSUE THREAD

**Issue by Keith94** [bwinton/VerticalTabs#415]
In the large tabs mode, the tab close button doesn't fit the full height of the tab when hovering it.

![snag 2016 07 18 07 11 13](https://cloud.githubusercontent.com/assets/5490615/16917561/fb8c155e-4cb6-11e6-907d-6976abee9aa4.png)

**Comment by ericawright** [comment]
@bwinton are we decided on full height, or top right corner?

**Comment by bwinton** [comment]
Smaller red box, top-right corner, I think.

**Comment by Keith94** [comment]
Good idea.
