### ISSUE TITLE
Activating tab center hides buttons on the same line as the tabs

### ISSUE THREAD

**Issue by valenting** [bwinton/VerticalTabs#417]
I have previously customized my UI to have the download button and progress on the same line as my tabs, on the right side of them.

After activating tab center, the button is missing, and I can't check on my downloads' progress.
To fix this, I had to disable tab center, move the button to another place, then reactivate tab center.

**Comment by bwinton** [comment]
Yes, that is how we've implemented it, and do not have any designs for how we would want to change it to allow customizable buttons in the tab area.  Thanks!

**Comment by valenting** [comment]
@bwinton 
Could you add a some code to move buttons out of the area when VerticalTabs is activated?
It was quite difficult for me to locate where the button went, and was only able to figure it out when the download finished and I saw an animation somewhere near the "New Tab" button.

**Comment by bwinton** [comment]
It's possible, but quickly gets complicated since we would also want to move them back on uninstall (or people would complain), but they may have customized their browser in the meantime, which makes it tricky to figure out where to put things…

**Comment by valenting** [comment]
Then maybe a notification at the time of install? "It looks like you have some buttons in the tab bar. They will be hidden unless you put them somewhere else." Or something like that.
