### ISSUE TITLE
[Visual] Should tab bar have a hard separator?

### ISSUE THREAD

**Issue by sevaan** [bwinton/VerticalTabs#418]
I just visited a site with a very similar grey sidebar and noticed that my tab bar seemed to disappear into the site content. Under the URL bar we have a dark separation line to separate it from the page content...do we need one on the sidebar too?

http://i.sevaan.com/0p1d11001X1m

**Comment by bwinton** [comment]
I also like the thin splitter, but I wanted it to be large enough to grab…

**Comment by bwinton** [comment]
Fixed in aa48828a8c14c333aeab2156b4d2faa62bd90bdb.
