### ISSUE TITLE
Tweak "maxVersion" in install.rdf?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#42]
**SPOILER ALERT:** I lack some basic knowledge of XPIs and add-ons in general.

Re: [/install.rdf:22](https://github.com/bwinton/VerticalTabs/blob/d911c4f972766c685904aa071a168b8b7d44072f/install.rdf#L22), 

```xml
    <em:targetApplication>
      <Description>
        <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id> <!-- Firefox -->
        <em:minVersion>29.0a1</em:minVersion>
        <em:maxVersion>47.0</em:maxVersion>
      </Description>
    </em:targetApplication>
```

Do we want an explicit `maxVersion` here, or will that mess some stuff up as stuff rides the trains and Nightly is currently v48.0a1.

**Comment by bwinton** [comment]
So, I just installed it on Nightly, and it seems to install and run just fine even with the maxVersion set to 47.0.  I don't know if we need an explicit maxVersion, though.

**Comment by johngruen** [comment]
@clouserw, maybe you could shed some light here/

**Comment by 6a68** [comment]
The easiest way to deal with maxVersion is to set it to `*`, so that there's no upper limit.

**Comment by 6a68** [comment]
MDN references: the [list of valid application version numbers](https://addons.mozilla.org/en-US/firefox/pages/appversions/) is linked from https://developer.mozilla.org/en-US/docs/Extension_Versioning,_Update_and_Compatibility
