### ISSUE TITLE
`control + t` opens tab at top 

### ISSUE THREAD

**Issue by jonasfj** [bwinton/VerticalTabs#422]
Clicking new tab open a new tab at the top, this is expected (and pretty awesome).

But hitting `control + t` should probably open a tab below the current tab.

The current flow completely breaks the case where you open a new tab to google something and then use `control + shift + tab` to navigate back to previous tab...

Firefox 47.0 (Ubuntu 16.04).

Unrelated: I would love to use `control + up/down` to switch between tabs... Actually, I would prefer `alt+up/down`, but it's already used by some websites.

**Comment by andreicristianpetcu** [comment]
I think it should open the tab at the bottom just like the current feature. Oppening them at the top is really strange.

Ctrl+Tab/Ctrl+Shift+Tab is a nice key combo for next/previous, a lot of apps are using it.

**Comment by andreicristianpetcu** [comment]
@jonasfj there is an option for opening tabs at the bottom. Go to about:addons > Tab Center Options > uncheck New tabs are opened at the top.

I would close this issue.

**Comment by jonasfj** [comment]
Ah, thanks...

**Comment by Keith94** [comment]
He asked for "open a tab below the current tab." I would like to see that as well.
