### ISSUE TITLE
Breaking bug when used with Tab Groups, the outdated native firefox extension

### ISSUE THREAD

**Issue by KingZee** [bwinton/VerticalTabs#424]
http://puu.sh/q9EwK/ef1659ca7b.jpg screenshot of what i had, i had to manually clear all the groups

**Comment by bwinton** [comment]
Yeah, we have problems with XUL caching stuff in our restartless extension.  It should be fine after a restart, though…

**Comment by Dimas-sc** [comment]
Restarting solves it partially. After the last update all the tab groups are mixed :-(

**Comment by simonbru** [comment]
The tabs are all mixed, but Tab groups still remembers in which group each tab belong.
I could fix the issue by disabling Tab Center, restarting Firefox and then switching group for some window where the tabs were mixed.

However I am really missing Tab Center now, didn't realize how much I got used to it.

**Comment by folz** [comment]
This also happened to me as the extension auto-updated to the most recent one, but I don't have Tab Groups. Didn't take a screenshot, but my firefox looked like the one in OP's.

**Comment by brainsik** [comment]
I'm also having issues with Tab Center + Tab Groups. Had the problem in the screenshot, but restarting got rid of that. The main problem is that when I open a link in a new tab, _all_ the tabs from _all_ the tab groups show up in the sidebar. Switching into the Tab Groups view and out again clears them out again.

I'd really like to rollback until this is fixed, though I'm not sure how. I've really grown to like Tab Center!

**Comment by ericawright** [comment]
duping to #464
