### ISSUE TITLE
All open tabs are fetched and thumbnailed in the background on launch, with about:newtab showing until fetched

### ISSUE THREAD

**Issue by rnewman** [bwinton/VerticalTabs#427]
Just updated, and now I get this:

![screenshot 2016-07-21 13 22 16](https://cloud.githubusercontent.com/assets/91722/17037564/71a6be88-4f46-11e6-8147-662cc82c4326.png)

**Comment by bwinton** [comment]
Hmm…  Firefox is pretty bad at thumbnails, but it should be better than that.  Can you cmd-tab over each of them and see if they refresh?

@ericawright For the next version, what do you think about looping over all the open tabs and getting thumbnails when the add-on is installed or updated?

**Comment by rnewman** [comment]
It looks like `about:newtab` was being screenshotted and used for each. It seems to have recovered now, and I see page thumbnails instead; perhaps it's a first-time-with-this-code bug, as you note?

Also of note: I use a blank page for new tabs, but it's still loading and screenshotting `about:newtab`, which causes some jank on Cmd-T. I'll file two separate issues for that.

**Comment by callahad** [comment]
Instead of what I'm actually seeing, the thumbnails show seem to show URLs as they would appear to a logged-out user on a different browser*. For GitHub, Twitter, and many other sites this results in incorrect and therefore useless and actively misleading thumbnails.

Very frustrating.

It also makes me wonder about resource use, tracking, etc. Is Tab Center sending all of my visited URLs, in real time, to a third-party screenshotting service? How much of my bandwidth is Tab Center wasting to download and render all of the media on twitter.com's splash page?

* Twitter's mobile site does a lot of UA sniffing. The thumbnail I see for m.twitter.com in a private window is also very different from the content I see in the private window itself. Evidently Twitter thinks a different browser is visiting it for purposes of the thumbnail than it does in the tab.

**Comment by rnewman** [comment]
Nope, after restarting, I'm back to most of my tabs having a thumbnail of `about:newtab`. After a minute or two they're trickling in, one at a time, with my laptop fan going.

Looking in Activity Monitor, it seems like Firefox is fetching every single page, even when I have tabs set to be zombies; about **100MB** so far. I have about 40 tabs open.

This is not OK.

@callahad: I expect that these thumbnails, like those on `about:newtab`, are fetched without cookies or other identifiers, in order to avoid odd side effects like marking your Facebook newsfeed as read. The downside is that the thumbnails are not of the page you viewed. For this reason, our mobile browsers screenshot the page as it loads, and save the screenshot.

@bwinton: can we roll back the thumbnail change? I don't think it's acceptable for Firefox to pull down 100MB of data each time I relaunch the browser — or, indeed, to background-fetch pages for thumbnailing at all. That's not expected behavior.

**Comment by bwinton** [comment]
I'm not inclined to roll back the thumbnail change, but I think it might be useful to look a little closer at [the Firefox code we're using](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/thumbnails/BackgroundPageThumbs.jsm?q=path%3ABackgroundPageThumbs&redirect_type=single#86) to see if there's a way to either not load thumbnails for zombie tabs, or make sure they hang around longer than you're seeing, or something else that will help.

I would also be more than happy for someone to improve Firefox's thumbnailing code, which would not only fix this, but a host of other problems as well…

Perhaps we could also steal the image code from Activity Stream, although I'm not really excited about the way that looks.

**Comment by rnewman** [comment]
It seems that the `BackgroundPageThumbs` fetch-based approach to thumbnailing is a bad fit for a tab UI, for several reasons:

* The logged-out view of a page is actively misleading. Try it: open a security bug. You'll see the "you don't have access to this bug" page in the thumbnail pop into the tab pane a few seconds after the page finishes loading. IMHO thumbnails are only useful if they really are thumbnails of the tab you'd get if you click them.

* It fetches and renders every page twice! (Tested by tailing my own server's access.log.)

Further:

* It doesn't seem to treat private windows differently… which means it either doesn't cache thumbnails (bad), or it caches private thumbnails (bad).

It's fine if you want to position this as a purely experimental add-on, and thus it's fine to use this approach to thumbnailing, but I was under the impression that it was suitable for use as a daily-driver, albeit one that changes color, or from a pick-up into a sedan, occasionally. I would not feel comfortable pushing this change — one that fetches every opened page twice, and every open tab on launch — out to 23,000 users. If I'm surprised, I bet many others are, too.

Instead, I might propose: capture thumbnails for tabs on load, using `PageThumbs.captureAndStore` (or the non-storing variant for private windows) and friends. That'll give you caching and use the already-fetched page, which would solve all of my concerns.

**Comment by rnewman** [comment]
Yes, this requires some kind of experience for when there's no thumbnail. On mobile platforms — where six thumbnails is your very first UI on launch — we use a key-colored block with favicon, or the grey globe if we don't even have that.

**Comment by bwinton** [comment]
>Instead, I might propose: capture thumbnails for tabs on load, using PageThumbs.captureAndStore (or the non-storing variant for private windows) and friends. That'll give you caching and use the already-fetched page, which would solve all of my concerns.

Works for me, and I think we could probably push that change out tomorrow.  Would `captureAndStoreIfStale` be even better (to avoid some re-fetches)?

**Comment by rnewman** [comment]
Yeah, I think so! Skimming suggests that there's some code in there to figure out if the thumbnail should be saved, so someone might have already taken care of the private browsing case…

**Comment by bwinton** [comment]
Awesome!  Thanks for the help, and I'll see about getting that fix in asap.  😃

**Comment by bwinton** [comment]
Okay, I've got a test branch up at https://github.com/bwinton/VerticalTabs/tree/switch-thumbnails.  If you want to try it out using the `Load Temporary Add-on` button in about:debugging, and see if it's any better, I'ld love to hear the results…

**Comment by rnewman** [comment]
Looks great!

Open a new tab:

<img width="260" alt="screenshot 2016-07-21 19 04 09" src="https://cloud.githubusercontent.com/assets/91722/17044570/0ee4e7d6-4f76-11e6-80dd-058c3410a461.png">

Open Facebook in that tab:

<img width="260" alt="screenshot 2016-07-21 19 04 23" src="https://cloud.githubusercontent.com/assets/91722/17044573/1546df26-4f76-11e6-9510-6d585fc5f928.png">

It might benefit from a spinner or some other visual change before page load is finished — right now it shows the previous thumbnail. But that's no different to the situation now before the background load has finished, and in fact shortens the time a little…

I have one tab that (even across reload) failed to thumbnail:

<img width="263" alt="screenshot 2016-07-21 19 08 04" src="https://cloud.githubusercontent.com/assets/91722/17044603/851373f0-4f76-11e6-8b65-11c4be907ab6.png">

**Comment by ericawright** [comment]
@bwinton your branch looks good. 
@rnewman  that seems to happen on certain pages, we haven't been able to work it out yet.
