### ISSUE TITLE
Verify contents on TestPilot site

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#43]
Re: http://testpilot.dev.mozaws.net/experiments/tabcenter

We should make sure all the data is accurate.
Specifically, I don't know what we need for Measurements or intros, screenshots, onboarding flows, privacy policies, etc.

**Comment by bwinton** [comment]
Where's the source for that (so that I can see what info we have without logging in)?

**Comment by ckprice** [comment]
> Where's the source for that (so that I can see what info we have without logging in)?

I sent you a note in channel (hopefully this is what you were looking for).

**Comment by bwinton** [comment]
All that data looks accurate to me.  We do need a better icon, but that's a different bug.  🙂
