### ISSUE TITLE
Allow thumbnailing to be disabled

### ISSUE THREAD

**Issue by rnewman** [bwinton/VerticalTabs#430]
I would prefer to have narrower rows (the same height as the 'X'), with a small favicon rather than a wide screenshot. On a 13" MBP it's impractical for me to have tabs this large.

**Comment by rnewman** [comment]
One of my windows decided it didn't want thumbnails, so I got to see the old and new experience side-by-side!

![screenshot 2016-07-21 13 57 40](https://cloud.githubusercontent.com/assets/91722/17038643/83d09afc-4f4b-11e6-9c7d-176e0496e1b6.png)

I have a pretty strong visual and interaction preference for the old, narrow style.

**Comment by bwinton** [comment]
If you don't have enough space, the large tabs will automatically compress down to the smaller one, and one of the things we're trying to test with this add-on is how people like the larger tabs.  (So your feedback is certainly taken into account, but I don't think we'll be adding this option.  But you should totally fork the code, and add it to your copy!  😉)

**Comment by rnewman** [comment]
Quite apart from the space usage, I want to stop the resource cost of fetching and thumbnailing…

**Comment by bwinton** [comment]
Yep, but disabling the feature is too heavy a hammer to try and solve that problem with.

**Comment by rnewman** [comment]
More thorough explanation of my feedback, at a keyboard: I find the thumbnail version has *less* value than the non-thumbnail version. Let's compare:

![screenshot 2016-07-21 17 20 59](https://cloud.githubusercontent.com/assets/91722/17043012/a0a0dcf2-4f67-11e6-9f15-c28b934b746d.png)![screenshot 2016-07-21 17 21 09](https://cloud.githubusercontent.com/assets/91722/17043017/a6b6234a-4f67-11e6-8350-9b0d7d851a8a.png)

With thumbnails I can see:

* Visual noise, but only one of these tabs gives me more information as a thumbnail (the picture of Rich Hickey).
  * 
  * 
  
* Less title, typically enough that I can read one fewer word.
  * 
  * 

* More space between lines, which makes it much harder to scan. (See what I mean?)
  * 
  * 

The close button also feels like a smaller target, and of course thumbnails aren't free.

**Comment by bwinton** [comment]
Good feedback!  We'll also be looking to see what the other testers think, but you raise some valid points.

(In the meantime, as previously mentioned, if you have more tabs than space, they'll automatically switch to small mode, so at least there's a workaround.)

**Comment by callahad** [comment]
I don't want to diverge from upstream. Would you be open to a noninvasive patch that makes it possible to force the smaller tabs via a single about:config setting? Looks like a extra conditional term in [verticaltabs.jsm](https://github.com/bwinton/VerticalTabs/blob/891887d549f870684db8a4840d75261776362aa2/verticaltabs.jsm#L640-L644) would be enough to do it.

**Comment by ericawright** [comment]
linking this to #439
