### ISSUE TITLE
Sometimes the pin sidebar button gets shrunk

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#44]
Found in 1.9

Haven't been able to find reproducible steps, but it just happens sometimes.

![add-ons_manager_and_new_tab](https://cloud.githubusercontent.com/assets/557895/14513535/9cb292ec-019d-11e6-861b-8f7e12ab5d01.png)

**Comment by johngruen** [comment]
@pdehaan I'm unable to repro...can you gif me?

**Comment by pdehaan** [comment]
I can't seem to reproduce this today.
Not sure if today's 1.9 build is different than my previous build. I'm installing the add-on from @bwinton's people.mozilla URL and /test.html.

@bwinton How often are you updating the http://people.mozilla.org/~bwinton/TabCenter/tab_center_test-1.9-fx.xpi XPI?

**Comment by bwinton** [comment]
Never.  (Each version should be consistent.  If I post a new one, it'll be at `tab_center_test-1.10.fx.xpi`.  I'll always put the latest version at `tab_center_test.xpi`, but in this case, I don't think there's a newer one.)
