### ISSUE TITLE
Regression: Pinned tabs are lost on restart

### ISSUE THREAD

**Issue by andreicristianpetcu** [bwinton/VerticalTabs#440]
1) Right click on a tab and click "Pin Tab" (it's color changes)
2) Restart Firefox the tab is lost

On normal Firefox regardless of the version the pinned tabs are kept while the new Tab Center looses them.

**Comment by wresuolc** [comment]
I'm on linux + nightly and can't reproduce this.

**Comment by ericawright** [comment]
I also can't reproduce this on osx + Dev Edition

**Comment by andreicristianpetcu** [comment]
Well..... this is embarrassing :( I updated to the latest nightly and the latest Tab Center and it does not reproduce. I'm closing it. Sorry for the noise.
