### ISSUE TITLE
Browser chrome suddenly breaks apart, literally, without noticeable user interaction

### ISSUE THREAD

**Issue by funtoosh** [bwinton/VerticalTabs#445]
OS: Mac OS 10.10.5
FF: Release, 47.0.1

This might have happened while the addon was updating (there were no tab thumbnails before, but they were there after the crash), but otherwise there was no user input, but merely a sudden change of GUI to sth. unresponsive looking like this:

![bildschirmfoto 2](https://cloud.githubusercontent.com/assets/506433/17065348/a44a018c-5041-11e6-8961-b75814733073.png)

Had to force quit, tabs could not be closed, new ones could be opened though, but remained invisible ...

Cheers,
-f

**Comment by ericawright** [comment]
Thanks, this is due to updating. It should be fixed after restarting Firefox. duping to #438
