### ISSUE TITLE
Shorten tab address for large tabs

### ISSUE THREAD

**Issue by Keith94** [bwinton/VerticalTabs#448]
It may be useful if you could remove the beginning part of the url ("http://www.") in order to fit more of the url on screen, since I usually keep my sidebar width rather narrow.

**Comment by bwinton** [comment]
Like this?
<img width="544" alt="screenshot 2016-07-22 16 48 14" src="https://cloud.githubusercontent.com/assets/159571/17070870/4dcc97e4-502c-11e6-9f4a-4ae0c8aef8de.png">

**Comment by Keith94** [comment]
Yes, displaying only the domain part is good enough imo.
