### ISSUE TITLE
Can't scroll all the way back to the top if you have lots of open tabs

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#45]
Found in 1.9

---

### Steps to reproduce:
1. Install the add-on.
2. Open lots of tabs.
3. Scroll to the bottom.
4. Scroll to the top.

### Actual results:

I can scroll 98% of the way to the top of the list, but not that pesky 2%. Not sure if it is because the first tab seems to be a "pinned tab", or what.

![mozilla_firefox_and_downloads_and_extract-xpi](https://cloud.githubusercontent.com/assets/557895/14513818/88cf4278-019f-11e6-98b3-653e49b9b724.png)

**Comment by 6a68** [comment]
Estimate: easy?

I can't repro this one, but based on the report, I'm guessing it's a minor CSS tweak.

**Comment by johngruen** [comment]
@pdehaan can you still do this...i changed some of the layout css recently and think i fixed it. want to pull, test and possibly close this?

**Comment by pdehaan** [comment]
I'm not seeing this locally anymore with latest code from GitHub. 👍 

Although I have about 40 open tabs and I'm seeing some scrolling issues. It seems that using my [Apple Not-So-Magic] Mouse (or trackpad) i cant scroll the tabs vertically when i scroll up or down. The list only moves if I manually click+drag on the scroll thumb, or if I hover over the scrollbar and then try scrolling the tab list vertically with my mouse.

**Comment by bwinton** [comment]
Related to #9, perhaps?

**Comment by bwinton** [comment]
Resolving fixed, and we'll track the scrolling problem in issue #81…
