### ISSUE TITLE
Tab Center breaks tab grouping with Tab Groups

### ISSUE THREAD

**Issue by jonalmeida** [bwinton/VerticalTabs#453]
Using the Tab Groups addon (previously called Panorama), the grouping is broken initially or during mouse over events. The way to resolve this currently is to toggle between the panorama view to have the tabs correctly show up in the tab tray. See the screenshots below for a better idea of the issue:

Tab grouping broken initially
<img width="200" alt="screen shot 2016-07-22 at 2 53 06 pm" src="https://cloud.githubusercontent.com/assets/1370580/17072430/0508566a-501d-11e6-9a17-30b599cb2647.png">

Panorama viewing shows the correct grouping for the tabs
<img width="1038" alt="screen shot 2016-07-22 at 2 54 39 pm" src="https://cloud.githubusercontent.com/assets/1370580/17072436/151252ae-501d-11e6-9fbf-02826be32303.png">

Coming back out of the panorama view correctly puts the appropriate tabs back into the tabs tray.
<img width="200" alt="screen shot 2016-07-22 at 2 54 55 pm" src="https://cloud.githubusercontent.com/assets/1370580/17072446/22ea6812-501d-11e6-8517-5e2baee3fae7.png">

**Comment by Celti** [comment]
I can confirm this issue and also note that it reverts back to the "ungrouped" tab bar every time I open a new tab.

**Comment by ericawright** [comment]
duping to #464

**Comment by brainsik** [comment]
Also reported in #499.
