### ISSUE TITLE
tabcenter disables (only) VimFx's help display

### ISSUE THREAD

**Issue by hwine** [bwinton/VerticalTabs#454]
The [VimFx addon](https://github.com/akhodakivskiy/VimFx) works fine with tabcenter -- except that the "help" dialog will not display. The help dialog is normally displayed from VimFX's normal mode by either:
 - typing '?'
 - clicking the VimFx icon in the toolbar

Neither method works when tab center is enabled. Both work when it is not enabled.

**Comment by ericawright** [comment]
duping to #464

**Comment by lydell** [comment]
This has now been fixed in VimFx. See akhodakivskiy/VimFx#834.
