### ISSUE TITLE
Remove inactive window style for tabs

### ISSUE THREAD

**Issue by Keith94** [bwinton/VerticalTabs#455]
https://github.com/bwinton/VerticalTabs/blob/master/skin/base.css#L457-L460

The current tab color changes when the window is inactive, but I don't see why, since by default Firefox doesn't have the same feature anyway.

**Comment by bwinton** [comment]
Firefox does change the active tab's colour when the window is inactive, and I don't see this as a huge problem, so I'm going to make the call that we won't change this behaviour.  Thanks for hte suggestion, though!

**Comment by Keith94** [comment]
Oh I didn't know that... my mistake.
