### ISSUE TITLE
YouTube fullscreen video is cut off when Tab Center is enabled

### ISSUE THREAD

**Issue by cpeterso** [bwinton/VerticalTabs#456]
STR:
1. Enable Tab Center.
2. Play a YouTube video.
3. Make the video full screen.

RESULT:
The full screen video is shifted to the right, leaving a white rectangle on the left side of the screen.

I see a similar problem with Persona's popup login windows.

I am using Tab Center 1.21 and Firefox 48–50.

**Comment by konfou** [comment]
This happens to me too when a site object tries to get fullscreen (html5/flash player or game) while sidebar is permanently opened. When sidebar is retraceable fullscreen works fine.

**Comment by Keith94** [comment]
Fixed by 78d194d
