### ISSUE TITLE
Can not change the tab order

### ISSUE THREAD

**Issue by KuoE0** [bwinton/VerticalTabs#458]
I opened a new page from the another page. And I want to drag it to change the order of tabs. But I can't do that!

**Comment by Keith94** [comment]
Do you use other tab-related add-ons, like Multiple Tab Handler?

**Comment by KuoE0** [comment]
Oh...yes, I use Multiple Tab Handler.

**Comment by Keith94** [comment]
It's a compatibility issue when both add-ons are installed. I reported it to the developer but didn't get a response yet. See piroor/multipletab#126

**Comment by ericawright** [comment]
duping to #464 464
