### ISSUE TITLE
Pinned+muted tabs move the speaker icon over the favicon

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#46]
Found in 1.9

---

### Steps to reproduce:
1. Install latest add-on.
2. Open a bunch of tabs.
3. Pin and mute a couple tabs (right click on the tab in the sidebar and select "Pin Tab" and "Mute Tab" respectively).
4. Mute a couple unpinned tabs.

### Actual results:
If a tab is pinned+muted, the mute speaker appears over the favicon.
If a tab is muted only, the mute speaker is right aligned.
Hovering over a muted tab, causes the muted icon to shift over by like 30px to make room for the red X icon.

![new_tab_and_new_tab_and_downloads](https://cloud.githubusercontent.com/assets/557895/14514181/45ddaea6-01a3-11e6-8620-bcb070a5a9e1.png)

### Expected results:
Not sure if we should always overlay the muted icon over the favicon. It looks good, and makes for a less shifty UI. But I defer to @johngruen's UX decisions.

**Comment by johngruen** [comment]
oof
