### ISSUE TITLE
Possible cross interaction with Tab Groups

### ISSUE THREAD

**Issue by Feagorn** [bwinton/VerticalTabs#469]
Beside TabCenter I have also the TabGroups extension installed.
All in all the two are working quite well together, but at times the tabs from all existing groups are poured into one really long list. After a few minutes or clicks and switching between tabs, the groups get separated again. This happens at random and I cannot tell if this is a problem on TabCenter or TabGroups.

**Comment by ericawright** [comment]
duping to #464
