### ISSUE TITLE
The add-on has some strange behaviors when a Lightweight Theme is installed or previewed.

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#48]
The header in the sidebar shrinks when the theme is enabled. Also, the toolbar buttons overlap with the sidebar when it auto-expands with a theme installed.

(From sec-review.)

**Comment by johngruen** [comment]
@bwinton can confirm this one, since i experienced it myself this morning :)

**Comment by johngruen** [comment]
![screen shot 2016-04-18 at 11 38 19 am](https://cloud.githubusercontent.com/assets/3323249/14610031/38d98378-055a-11e6-86ab-b3d31836c6c1.png)
![screen shot 2016-04-18 at 11 38 13 am](https://cloud.githubusercontent.com/assets/3323249/14610032/38dbe546-055a-11e6-941d-e40e6da7fd4a.png)

**Comment by bwinton** [comment]
Newtab header set to transparent in a couple of places, iirc.
Should be quick to fix.
