### ISSUE TITLE
Pinned sidebar settings aren't persisted betweenst windows

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#51]
Found in 1.9

---

### Steps to reproduce:
1. Install the Tab Center Test add-on.
2. Open a couple tabs and make sure your sidebar is pinned.
3. Open a new window (_File > New Window_ or _File > New Private Window_).

### Actual results:
The new windows don't have pinned sidebars, which can be mildly annoying if you have to re-enable pinned tabs in each browser window you open.

### Expected results:
Persist that setting between windows/sessions.

**Comment by bwinton** [comment]
So, this is kind of interesting…  If I have three windows open already, and pin the sidebar in one of them, should it be pinned in all the others?  If not, then when I open a new window, should it be pinned or not?
(I agree that it should persist across sessions, though…)
