### ISSUE TITLE
Pinning Breaks layout in 1.9

### ISSUE THREAD

**Issue by johngruen** [bwinton/VerticalTabs#53]
In 1.9 (54a16d217d6) Pinning overlaps the browser chrome and creates a big blank space on the right hand side of the browser: 
![screen shot 2016-04-18 at 11 13 15 am](https://cloud.githubusercontent.com/assets/3323249/14609246/016c6cfa-0557-11e6-9f4a-6909ebc2786f.png)

**Comment by 6a68** [comment]
Looks like an easy fix to me: when the tabcenter is pinned, `#appcontent` (the thing that holds the visible web page) needs to have its `left` value overridden, from the default 45px to 260px. Easy to verify this, just give it a try in the Browser Toolbox.

**Comment by bwinton** [comment]
Yeah, but why didn't it do that before?  (Also, I suspect we want to change `#panel-3-1`, so that the DevTools and Findbar are also scrolled over)
