### ISSUE TITLE
Truncation rules are different if you are hovering over the tab sidebar

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#56]
Found in 1.9

---

Another pointless little nit.

### Steps to reproduce:

1. Add a bunch of tabs with longer titles. I usually browse to reddit.com/r/worldnews and open ~10 links in new tabs.
2. Pin the sidebar (not relevant, but makes it easier to see -- although this happens regardless).
3. Note  that the titles in the sidebar aren't truncated, they just get get clipped. (See **Figure 1** below.)
4. Hover over an item in the sidebar. Titles should now get truncated. (See **Figure 2** below.)

### Actual results:

![ed_miliband_says_panama_papers_show_ wealth_does_not_trickle_down ___uk_politics___news___the_independent](https://cloud.githubusercontent.com/assets/557895/14619621/28cc8904-056d-11e6-98cc-b103e5599cef.png)
**Figure 1:** When not hovering over the sidebar, there are no "..." at the end of the titles.

---

![new_tab_and_ed_miliband_says_panama_papers_show_ wealth_does_not_trickle_down ___uk_politics___news___the_independent_and_mozilla_-_calendar_-_week_of_apr_18__2016_and_twitter_-__private_browsing_](https://cloud.githubusercontent.com/assets/557895/14619655/4c21081c-056d-11e6-80b5-bad4c8e0ecdf.png)
**Figure 2:** When hovering over sidebar, the ellipsis ("...") is added. You can see in the screenshot that I'm hovering over a "New Tab" and all the longer link titles get ellipsis truncated titles. Not sure if this is causing lots of redraws or what. Or if it's just always easier to truncate with "...".

**Comment by bwinton** [comment]
Right, so we do that because we don't want the ellipses when the tabs are collapsed (as so):
<img width="58" alt="screenshot 2016-04-26 15 45 45" src="https://cloud.githubusercontent.com/assets/159571/14832000/0c130072-0bc6-11e6-8ad9-43f4739149e8.png">

But, I think I agree that we should have them always when the sidebar is expanded, so I'm going to try doing that.

**Comment by carbin** [comment]
Can it be changed so that the titles expand after the sidebar is collapsed, or while it is collapsing, so that you can't see it happening? It is weirdly distracting when the titles all expand just before the sidebar starts closing.
