### ISSUE TITLE
Weird tab duplication when changing tabs with caret dropdown menu

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#57]
Found in 1.9

---

### Steps to reproduce:
0. Make sure the TabCenter add-on is installed (using the /test.html version)
1. Open a few tabs.
2. Make sure your sidebar is NOT pinned.
3. Hover over the tab sidebar.
4. Expand the open links by hovering over the caret in the sidebar and choosing a not-active tab.
5. Repeat 5.

### Actual results:

![tab-madness](https://cloud.githubusercontent.com/assets/557895/14620758/6cf3eaa4-0573-11e6-96c3-cdb352fa81de.gif)
**Figure 1:** Not sure what happened to my color-palette here, so sorry for the blown out colors. Hopefully gets the general idea across though.

You can see I only have 2 actual tabs open, but for some reason the caret menu duplicates them so the dropdown shows 16 items (with several checkmarks).

**Comment by bwinton** [comment]
Look into it for 10 minutes, but we can always use the `display: none` hacky-fix.
