### ISSUE TITLE
Sometimes the main window shrinks to a few pixels high

### ISSUE THREAD

**Issue by 6a68** [bwinton/VerticalTabs#59]
I don't really know how I triggered this, but I've run into it twice this evening. That tiny sliver that says 'tab center test' is the about:addons page 😿 

<img width="1047" alt="screen shot 2016-04-18 at 7 10 33 pm" src="https://cloud.githubusercontent.com/assets/96396/14625600/54da1e9a-0599-11e6-8b25-a97103b1d00a.png">

**Comment by pdehaan** [comment]
Was able to reproduce on v1.10 this morning.

![mozilla_firefox_start_page](https://cloud.githubusercontent.com/assets/557895/14649828/9ef6d494-061d-11e6-9f38-0fda9f7619db.png)

**Comment by edmoz** [comment]
I see something like this when i pin and unpin the whole sidebar

**Comment by bwinton** [comment]
Can reproduce by opening a new window.  😭
