### ISSUE TITLE
Auto-updates not working

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#60]
It looks like we released [1.10](https://github.com/bwinton/VerticalTabs/tree/v1.10) today, but when I try and update my TabCenter@1.9 from yesterday, about:addons says "No updates found".

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14649092/63b7c08a-061a-11e6-9f9a-d716f66101bf.png)

I don't know anything about anything, but in some other projects, we have an update.rdf file as well which we host which we usually host on S3 or people.mozilla (or whetever) and reference from the install.rdf file (see [**universal-search** /install.rdf](https://github.com/mozilla/universal-search/blob/28a78f1238bc298fff6beaa4a53d3467229bbb4f/install.rdf#L15) example, or the [/update.rdf](https://github.com/mozilla/universal-search/blob/28a78f1238bc298fff6beaa4a53d3467229bbb4f/update.rdf#L15) file).

**Comment by johngruen** [comment]
what does testpilot want to do here?

**Comment by johngruen** [comment]
@clouserw could you take a look at this?

**Comment by wresuolc** [comment]
Yes, we'll need an update.rdf file somewhere.  We can either host it somewhere, or, the easiest method, would be to just put the add-on on AMO and it does all that for you.  It does mean you'd need to go through their review queue so it would be best to do once you have a final version.
