### ISSUE TITLE
Browser windows sometimes get corrupted after disabling the add-on

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#61]
Found in today's v1.10 build, but I've occasionally seen this earlier as well.

After disabling the add-on, the UI doesn't return to it's original state, and requires me to force-quit the add-on.

<img width="479" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/14650709/b772f6ac-0621-11e6-878d-39495574b300.png">

**Comment by 6a68** [comment]
There are a lot of bugs in the add-on that aren't resolved by removing the add-on, but are resolved by removing / disabling, then restarting. This bug report might correspond to any of the known open bugs, or some unknown ones, so it's probably too general to be investigated.

I vote for closing it, @bwinton's call though.

**Comment by pdehaan** [comment]
@6a68 Here's an example of me stopping the TabCenter experiment through Test Pilot.

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/14652531/939b6c0c-0629-11e6-8b6c-1da431f5fe4d.png)

Resizing the browser didn't solve anything, and the only way I could get my browser usable again was to switch to fullscreen mode on OS X and then exit fullscreen.

**Comment by bwinton** [comment]
Can we get a copy of the Browser Console log first, to see if we can identify what's going wrong?

--

**Comment by pdehaan** [comment]
Not sure how much (if any) of this helps, but it looks like all the "pad.js" stuff is from etherpad.

This error pops up a few times though and may be a bit suspect:

> _"Could not read chrome manifest 'file:///Users/pdehaan/dev/tmp/ff-tool/_temp/browsers/FirefoxBeta.app/Contents/Resources/chrome.manifest'."_

---

![browser_console_and_firefox_test_pilot_-_tab_center_and__london_all_hands__submit_your_ elective _idea_by_may_3_-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/14652836/fdcf377e-062a-11e6-8274-0e3957d9c360.png)

**Comment by bwinton** [comment]
Also, how does Test Pilot uninstall add-ons?

**Comment by pdehaan** [comment]
I think this is the TestPilot `uninstallExperiment()` code we seek:
```js
function uninstallExperiment(experiment) {
  if (isTestpilotAddonID(experiment.addon_id)) {
    AddonManager.getAddonByID(experiment.addon_id, a => {
      if (a) { a.uninstall(); }
    });
  }
}
```
 via [/addon/index.js:346-352](https://github.com/mozilla/testpilot/blob/a41e42424096277f7fa0504baf5bca046b9ae346/addon/index.js#L346-L352)

/cc @meandavejustice @lmorchard

**Comment by meandavejustice** [comment]
Indeed. It is.

**Comment by pdehaan** [comment]
... I cannot reproduce this issue w/ my Nightly browser.

In fact, here's the output of my Browser Console (with all my other add-ons disabled):

![browser_console](https://cloud.githubusercontent.com/assets/557895/14654291/ce84c766-0631-11e6-8a3b-2aa8192dd920.png)

So I'm seeing the same "Could not read chrome manifest" message, and the "expression closures are deprecated" warning messages seem to come from [/utils.js:63](https://github.com/bwinton/VerticalTabs/blob/7a1f0431024634a57ceb3faa8aa93b8ec8ac0e36/utils.js#L63).

**Comment by bwinton** [comment]
@pdehaan Just as a question, do you have more than one Firefox window open when this happens?
