### ISSUE TITLE
Cannot use Bookmarks or History sidebars with TabCenter

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#62]
Found in v1.10

---

### Steps to reproduce:
1. Install the latest TabCenter add-on.
2. Enable the Bookmarks or History sidebar using the "View > Sidebar > Bookmarks" or "View > Sidebar > History" menu options.
3. Nothing happens (if the add-on is enabled).
4. Disable the add-on.

### Actual results:
The Bookmarks or History sidebars don't seem to activate when the add-on is enabled.

### Expected results:
The features should still work? Not too sure. Unfortunate that we break functionality, but managing

**Comment by johngruen** [comment]
![screen shot 2016-04-18 at 11 43 33 am](https://cloud.githubusercontent.com/assets/3323249/14610216/f213beda-055a-11e6-96ff-be03f9d00585.png)

**Comment by johngruen** [comment]
in the above screenshot, notice the history sidebar is semi-visible behind tab center.

**Comment by bwinton** [comment]
Ideally it would go `sidebar | tabs | content`.  But maybe also `tabs | content | sidebar`, if that's easier…

**Comment by javaun** [comment]
This is a common issue mentioned in feedback by users uninstalling

**Comment by xcombelle** [comment]
i came here to signal that. For me it looks more a bug than a feature request.

**Comment by pdehaan** [comment]
A user, @Qhue, reported in https://github.com/mozilla/testpilot/issues/844 that you can get into some glitchy UI when you open the sidebar with Ctrl+B (Command+B on Mac) using your keyboard.

---

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/15258340/d7271f00-18ff-11e6-9251-935f79b41df8.png)
**Figure 1:** Unpinned **Tab Center** sidebar.

---

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/15258360/f483cfe4-18ff-11e6-8b54-33bbc56e96b6.png)
**Figure 2:** Pinned **Tab Center** sidebar.

**Comment by bwinton** [comment]
Preview:
![sidebar](https://cloud.githubusercontent.com/assets/159571/15261834/9bb656ca-192c-11e6-9910-db129ff07c4b.gif)

**Comment by pdehaan** [comment]
![](https://media.giphy.com/media/AP35bRdoSqm9G/giphy.gif)
