### ISSUE TITLE
Add update.rdf manifest to support auto-updating add-on

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#66]
From IRC:

> - 10:32 AM \<pdehaan\> @bwinton: i dont think TabCenter auto-updates are working. I have 1.9 installed from yesterday and am trying about:addons "Check for Updates" and it says "no updates found".
> - 10:32 AM \<pdehaan\> do we have an update.rdf hosted somewhere that this is validating against?

> - 7:49 AM \<bwinton\> pdehaan: Nope, no update.rdf anywhere.  We could add one, but where should it point?  Or is that something TestPilot should handle, to avoid messing with users in the middle of tests unless necessary?

> - 9:21 AM \<pdehaan\> bwinton: I'm not too familiar with add-ons, but i thought the update.rdf usually goes beside the my-cool-addon.xpi, and then our install.rdf references the full URL to the update.rdf so that users will know when a new version of the add-on is available.
> - 9:22 AM \<pdehaan\> so in our case, we'd host it in your people account. which then brings up the question of where are we going to be hosting the add-on from (assuming we don't want to ship a testpilot experiment from your people.moz acct vs an S3 bucket or something)
> - 9:22 AM \<pdehaan\> but we should ping @clouserw or somebody with more add-on experience than i.

I was testing some other unrelated thing today and spotted this in my Terminal window:

| Timenstampen? | Thing | Level | Message |
|----|----|----|----|
| 1461360516952 | `addons.xpi-utils` | WARN | Disabling foreign installed add-on tabcentertest1@mozilla.com in app-profile
| 1461361118310 | `addons.update-checker` | WARN | Update manifest for tabcentertest1@mozilla.com did not contain an updates property

I don't think the first thing is important (I was trying to use `mozprofile` CLI to preinstall the add-on into a new profile), but the second warning seems specific to the manifest not having an `updates` property.

**Comment by wresuolc** [comment]
yeah, you'll need to host an update.rdf.  you could use github to host it if you want, or, if the add-on is done, we could upload it to AMO and have it handle it for you

**Comment by johngruen** [comment]
<blockquote>Yes, we'll need an update.rdf file somewhere. We can either host it somewhere, or, the easiest method, would be to just put the add-on on AMO and it does all that for you. It does mean you'd need to go through their review queue so it would be best to do once you have a final version.</blockquote>

**Comment by pdehaan** [comment]
Yeah, currently we're hosting the XPI from people.mozilla.org/~bwinton, but I assume we'll want to move that to S3 or AMO before we launch (but probably not necessary for this week's internal release).
