### ISSUE TITLE
Browser Console error when disabling the add-on via Test Pilot

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#67]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14803001/9103e7cc-0b0a-11e6-84ac-6d8ee74f23a5.png)

---

### Steps to reproduce:
1. Log into testpilot.dev.mozaws and install the Tab Center add-on.
2. Open the Browser Console (Tools > Web Developer > Browser Console)
3. Disable the Tab Center add-on via Test Pilot.

### Actual results:
I'm seeing this error in the Browser Console logs:

![browser_console_and_jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_8f25a7be-7cef-4680-9ab6-fd20a65b5a36_extensions_tabcentertest1_mozilla_com_xpi__utils_js_and_1__npm_run_once__node_](https://cloud.githubusercontent.com/assets/557895/14802947/0be21028-0b0a-11e6-8c45-cb4dfd5139fe.png)

> 17:15:35.130 Exception { message: "Component returned failure code: 0x…", result: 2147746065, name: "NS_ERROR_NOT_AVAILABLE", filename: "resource://tabcenter/verticaltabs.j…", lineNumber: 123, columnNumber: 0, data: null, stack: "VerticalTabs.prototype.installStyle…", location: XPCWrappedNative_NoHelper }1 [utils.js:117](https://github.com/bwinton/VerticalTabs/blob/7a1f0431024634a57ceb3faa8aa93b8ec8ac0e36/utils.js#L117)

Slightly tricky to debug since it seems to trigger on uninstall. So the links are broken by the time you get the error (since the add-on is disabled). So re-enabling the add-on and clicking the ["utils.js:117" link takes you here](https://github.com/bwinton/VerticalTabs/blob/7a1f0431024634a57ceb3faa8aa93b8ec8ac0e36/utils.js#L117).

**Comment by bwinton** [comment]
I'm pretty sure I fixed this in 2d80d7957cab43d1d82c34ca622283f781cc020e, but I found another bug while testing…
