### ISSUE TITLE
context menu item on bookmark bar is disabled / greyed out

### ISSUE THREAD

**Issue by edmoz** [bwinton/VerticalTabs#71]
1. install tab center (i'm on nightly mac)
2. view bookmark bar
3. context menu click on a bookmark in bookmark bar

actual: all items are grey and disabled

<img width="713" alt="screen shot 2016-04-26 at 2 11 41 pm" src="https://cloud.githubusercontent.com/assets/3698618/14834341/d948b522-0bb8-11e6-9c19-6cc820f08064.png">

expected: should be black and active

**Comment by bwinton** [comment]
I can't seem to reproduce this…  Do you have any other add-ons active?  (Like that one that's showing "Reload Favorite Icons"?)  Can you open the Browser Console with ⌘-⇧-J, and let me know if there are any messages there from verticaltabs (or anything else that looks suspicious)?

**Comment by johngruen** [comment]
I can't repro either paging @edmoz

**Comment by edmoz** [comment]
Looks like removing 'Favicon reloader addon fixed it.'  There must be some conflict but let's close this for now and revisit if more instances occur.
