### ISSUE TITLE
When uninstalling TabCenter, the browser Titlebar is left on.

### ISSUE THREAD

**Issue by sevaan** [bwinton/VerticalTabs#73]
STR.

1. Install TabCenter.
2. Through add-ons manager, disable TabCenter.
3. Tabs return to top of window, but browser titlebar is still on.

The fix is to manually go in to customize mode again after and turn off the titlebar from there. But if the user had it off already, it should return to that state.

**Comment by johngruen** [comment]
What's your version?

**Comment by sevaan** [comment]
Ah, this was on Nightly 49.0a1 (2016-04-27).

**Comment by johngruen** [comment]
@sevaan What version of tab center?

**Comment by sevaan** [comment]
I have removed the plugin, but it must have been an old version because the
titlebar goes away in 1.11. We can mark this resolved.

**Comment by bwinton** [comment]
Resolved as per original reporter.

**Comment by potch** [comment]
I just experienced this- disabling Tab Center did not remove the titlebar.
