### ISSUE TITLE
1.1 is definitely cropping the bottom few pixels of the browser

### ISSUE THREAD

**Issue by johngruen** [bwinton/VerticalTabs#74]
![screen shot 2016-04-27 at 12 57 24 pm](https://cloud.githubusercontent.com/assets/3323249/14860601/a2487aca-0c77-11e6-997c-2377f05e646e.png)

note the lack of input on the console (it's hidden under the bottom of the window)

**Comment by cpeterso** [comment]
I see this problem with irccloud.com's input field at the bottom of the page.

**Comment by ncubeeight** [comment]
This issue also makes it impossible to read the messenger conversations on Facebook.com because each conversation is pinned to the bottom of the page.

**Comment by bwinton** [comment]
I _think_ this was also fixed by e3bcf62fe36e61a9e0cd4e3f59a1f8bc6a034a6f…
