### ISSUE TITLE
Pinned tabs stay vertical after uninstalling

### ISSUE THREAD

**Issue by wresuolc** [bwinton/VerticalTabs#76]
I'm using Tab Center Test 1.11 in nightly.  After uninstalling my pinned tabs remain vertical:

![tc-vert](https://cloud.githubusercontent.com/assets/16946141/14861803/9cf5ae76-0c63-11e6-9e23-e270b19450bc.png)

**Comment by bwinton** [comment]
@sevaan saw something like this, too…

**Comment by wresuolc** [comment]
I didn't file a separate bug because I assume it's all related, but if you then right click and close one of those vertical tabs, it really messes things up -- all tabs but two disappear, one in the top left, and one on the right, about halfway down

**Comment by bwinton** [comment]
Hmm, looks like it's something in the _positionPinnedTabs function in vertical-tabbrowser.xml…
