### ISSUE TITLE
Lightweight themes sometimes show up on tabs

### ISSUE THREAD

**Issue by wresuolc** [bwinton/VerticalTabs#77]
I have a theme installed and it shows up on tabs when I first enable the add-on.  I'm using Tab Center Test 1.11 in nightly.  Screenshot:

![tc-bg](https://cloud.githubusercontent.com/assets/16946141/14861849/c8742eb0-0c63-11e6-838a-450ef4087fc1.png)

**Comment by wresuolc** [comment]
It just happens to match my theme, but it's not a part of it.  It's the pinned tab activity indicator, but all stretched out because the tab is wide!

**Comment by bwinton** [comment]
So, I stole the DevTools indicator, and got it looking like this…
<img width="289" alt="screenshot 2016-04-29 10 25 50" src="https://cloud.githubusercontent.com/assets/159571/14919022/c7e95e9c-0df4-11e6-9716-c80ac436f38d.png">

Any tweaks before I check it in, John?
