### ISSUE TITLE
First tab is always called New Tab

### ISSUE THREAD

**Issue by wresuolc** [bwinton/VerticalTabs#78]
I'm using Tab Center Test 1.11 on nightly.  The first tab in a window is always called New Tab for me (despite having loaded a site), regardless of whether it is pinned or not.  Screenshot:

![tc-bg](https://cloud.githubusercontent.com/assets/16946141/14861901/06468e22-0c64-11e6-9ed5-a204a461efd5.png)

**Comment by johngruen** [comment]
huh? can't repro...

**Comment by wresuolc** [comment]
Weird.  Happens to me every time, but fixes itself after a restart.

**Comment by lundjordan** [comment]
I saw this too initially. Maybe it was a ff restart or refresh of first tab but I haven't seen it since.

p.s. <3'ing tab center

version: at the time of this issue I was on 46.0 RC (beta channel)

**Comment by ericawright** [comment]
Reopening as I was able to reproduce.
How to reproduce - enable and disable tab center a few times, eventually the first tab's title will be "New Tab" both while enabled and while disabled.

enabled:
![screen shot 2016-05-17 at 11 18 28 am](https://cloud.githubusercontent.com/assets/10803178/15331248/732af6ca-1c2e-11e6-9dc3-5084cecd7c85.png)

disabled:
![screen shot 2016-05-17 at 12 50 09 pm](https://cloud.githubusercontent.com/assets/10803178/15331260/7e1838a4-1c2e-11e6-978b-558c7251868d.png)

**Comment by wresuolc** [comment]
We think #226 will fix this

**Comment by wresuolc** [comment]
semi-duping this!
