### ISSUE TITLE
Prototype seems to cut off the bottom of the content window.

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#8]
As reported by @campd.  Screenshot incoming, hopefully…  :wink:

**Comment by MattGrimes** [comment]
I'm seeing the same thing. This screenshot is as far down on the screen as OS X will let me capture. You can see I'm still missing half of the input box.
<img width="945" alt="screen shot 2016-03-29 at 10 13 03 am" src="https://cloud.githubusercontent.com/assets/6538151/14116993/632565f2-f597-11e5-88fb-e412de172c3d.png">
