### ISSUE TITLE
Tabs don't scroll with trackpad gestures

### ISSUE THREAD

**Issue by chuckharmston** [bwinton/VerticalTabs#81]
The list of tabs does not scroll when using gestures (i.e. two fingers + up or down). Presumably this is also the case with mouse wheels scrolls, but I don't have the hardware to test.

**Comment by bwinton** [comment]
Related to #9, perhaps?

**Comment by chuckharmston** [comment]
Possibly! Although that appears to have been resolved, so it's probably a regression in something.

**Comment by chuckharmston** [comment]
:heartbeat:
