### ISSUE TITLE
Weird effect when uninstalling

### ISSUE THREAD

**Issue by ianb** [bwinton/VerticalTabs#82]
This didn't happen the first time I uninstalled Tab Center, but after reinstalling and uninstalling it happened:

<img width="1356" alt="screen shot 2016-04-28 at 4 07 45 pm" src="https://cloud.githubusercontent.com/assets/44390/14901567/9f34976c-0d5b-11e6-9ae5-2a921e0125e6.png">

**Comment by johngruen** [comment]
Trippy

**Comment by bwinton** [comment]
(I think this was from an older version.  Ian has mentioned that he can't replicate it, but I want to leave this open for a few days to see if anyone else it running into something similar.)

**Comment by ianb** [comment]
This was from the version I installed from the Test Pilot site

**Comment by bwinton** [comment]
I think I'm going to close this, since no-one else has reported it, and it seems unreplicable.
