### ISSUE TITLE
Using keyboard shortcuts is now broken.

### ISSUE THREAD

**Issue by bteiger** [bwinton/VerticalTabs#86]
Mac OS 10.11.4
Using "Command +1" or "Command +2" allows you to cycle through open tabs. this works fine for the first 3 times then it stops working on the 4th try. 

Clicking on another open tab resets the count to 4 tries again.

**Comment by johngruen** [comment]
@bteiger can't repro...what version of Firefox are you on?

**Comment by bteiger** [comment]
45.0.2  did a restart of Firefox after enabling and that seems to have cleared it up.

**Comment by bwinton** [comment]
Resolving as fixed.  Thanks!
