### ISSUE TITLE
New Tab button underflows OSX buttons if you disable Title Bar

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#87]
Found in 1.12.

---

### Steps to reproduce:
1. Download and install latest Tab Center add-on.
2. Select Hamburglar menu > Customize.
3. Disable the Title Bar (toggle button in lower-left corner).
4. Click [Exit Customize] button to return to Firefox.

### Actual results:
<img width="868" alt="firefox_test_pilot_-_tab_center_and_slack_and_irccloud" src="https://cloud.githubusercontent.com/assets/557895/14905338/77356576-0d64-11e6-9848-8ecced5d678a.png">

### Expected results:
I don't know. I'm guessing this may just be fact-of-life, but just wanted to throw it out there in case there is anything we can do here.

**Comment by johngruen** [comment]
@bwinton can we force the title bar to be on?

**Comment by bwinton** [comment]
Well, probably, but for now I think I'm just going to hide that button.  ;)

**Comment by ciastek** [comment]
Is there a reason, why Tab Center isn't placed under the `#nav-bar`, like other sidebars actually do?
It'd be pretty!
![screen shot 2016-11-14 at 18 07 06](https://cloud.githubusercontent.com/assets/637051/20275079/6181bca4-aa97-11e6-95b0-b106f54d750f.png)
![screen shot 2016-11-14 at 18 07 19](https://cloud.githubusercontent.com/assets/637051/20275082/6578a26e-aa97-11e6-9b7d-95065d4b839a.png)

**Comment by bwinton** [comment]
Yes, it's for the same reason that the tabs are above the urlbar in tabs-on-top mode.  The content of the urlbar is determined by which tab you've selected, and to indicate that, the tabs should have a higher position in the visual heirarchy.  🙂
