### ISSUE TITLE
No visual indication of pinned tabs

### ISSUE THREAD

**Issue by Verdi** [bwinton/VerticalTabs#90]
I can't tell which of my tabs are pinned unless I right-click on them and read the context menu.

**Comment by bwinton** [comment]
Any thoughts on how we could show them as different?  @johngruen?

**Comment by johngruen** [comment]
@bwinton gimme a minute to scratch my head

**Comment by Verdi** [comment]
Replace the close button with an always visible pin? Then they can be closed by right-clicking, kind of like normal pinned tabs.

**Comment by johngruen** [comment]
@verdi...seems like an awful lot of pins, maybe we just draw an rule under then last pinned tab and hide the x, show a pin on hover?

**Comment by Verdi** [comment]
@johngruen Yeah that could work!

**Comment by johngruen** [comment]
o/, consulting @shorlander we'll figure out an easy path forward, but it will be something like this

**Comment by bwinton** [comment]
So, it's shockingly hard to draw a rule under the last pinned tab (unless you don't mind the rule being dragged when we drag the tab)…  Which might be okay for the first version.

**Comment by johngruen** [comment]
@bwinton...here's the plan

1. replace the x with a pin on hover
2. add a light blue left border (similar to the active tab), using #0996f8
3. Let's try adding a rule after the last one, but for the sake of keeping pixels aligned, you may need to convert all the tabs to border-box or use an inset box-shadow

**Comment by bwinton** [comment]
So, I've implemented some of these, and I think it's kinda good.  Get latest, give it a run, and let me know how you like it.
(Replacing the "x" is slightly tricky, since it'll still be a close button, but I'm not sure we need to show the pin.  Similarly, always showing the blue border feels to me like it might be enough that we don't need the rule under the bottom…)

**Comment by johngruen** [comment]
I'll check it out

**Comment by bwinton** [comment]
Thanks!  :wink:

**Comment by johngruen** [comment]
@bwinton...looks good, seeing a gap in the contracted tab view
![screen shot 2016-05-02 at 11 19 41 am](https://cloud.githubusercontent.com/assets/3323249/14958270/ea2e34cc-1057-11e6-9864-cb934847a7ed.png)
