### ISSUE TITLE
feature request: width of tab column

### ISSUE THREAD

**Issue by bteiger** [bwinton/VerticalTabs#92]
It would be fantastic if there is would be an option to have the tab column only show the favicons.  This would make things a bit more tidy along the side of the window.

**Comment by andymckay** [comment]
I would like it if I could just choose the width by dragging the divider. This would also eliminate the pin button?

**Comment by bwinton** [comment]
Dupe of #23.  :)  (Also, we would still want the pin button.  We introduced it because people complained about having to drag the width too much.)
