### ISSUE TITLE
feature request: pinned tab support

### ISSUE THREAD

**Issue by lundjordan** [bwinton/VerticalTabs#94]
example pinned squares at the top: https://lh4.googleusercontent.com/-pZ6TULZKO2M/UDDamSn2GYI/AAAAAAAACNU/nlpEEglVhmE/s1024/tree-style-tab.png

please close if this is not something you would like to support or you are tracking elsewhere.

<3ing tabbed center by the way 👍

**Comment by bwinton** [comment]
They're already supported!  (The top four tabs here are pinned.)
<img width="280" alt="screenshot 2016-05-03 12 17 54" src="https://cloud.githubusercontent.com/assets/159571/14990131/20c86a30-1129-11e6-829c-abb120557902.png">

It's unlikely that we'll make them squares, though, for a variety of reasons (largely technical)…  :wink:

**Comment by lundjordan** [comment]
ah, I just realized the colour sidebar. That's cool!

Too bad about the technical challenge, maybe one day we can revisit and find a way to take up less space in the sidebar with pinned tabs :)

thanks for the quick response

**Comment by bwinton** [comment]
(Just for reference, the non-technical issue is “What would they do when the sidebar is collapsed?”… :)
