### ISSUE TITLE
feature request: support nested tabs

### ISSUE THREAD

**Issue by lundjordan** [bwinton/VerticalTabs#96]
this feature is like combining tab groups into vertical tabs.

example: when a new tab (child) is opened from another tab (parent, it defaults to being nested (indented from parent). This expresses categories/tasks when browsing.

**Comment by bwinton** [comment]
Nope.  😀  Tree-style tabs is an add-on that people who want this kind of feature should use!  This experiment aims at a simpler interaction model.  (Although we may run another experiment later to test something along those lines…)

**Comment by lundjordan** [comment]
ah makes sense. thanks for the reply :)

**Comment by mimoo** [comment]
Ah, I was using this add-on in hope that it would have nested tabs one day. I guess I'll go back to Tree-Style tabs :(
