### ISSUE TITLE
full screen support

### ISSUE THREAD

**Issue by andymckay** [bwinton/VerticalTabs#97]
It would be awesome if full screen hid the vertical tabs.

**Comment by bwinton** [comment]
Hmm.  That should be fixed as part of #1.  Can you post a screenshot?

**Comment by andymckay** [comment]
Oh crap it is, I must have been using an old build. Sorry!

**Comment by andymckay** [comment]
Oh and that's awesome btw.

**Comment by bwinton** [comment]
\o/  😀
