### ISSUE TITLE
DEPRECATION WARNING: This path to Console.jsm is deprecated

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#98]
> _"DEPRECATION WARNING: This path to Console.jsm is deprecated.  Please use Cu.import("resource://gre/modules/Console.jsm") to load this module."_

Randomly spotted this in Browser Console, and it seems to trace back to [verticaltabs.jsm:43](https://github.com/bwinton/VerticalTabs/blob/5d5b1d726ef3c4c3a94901909bf2b010c9ac2390/verticaltabs.jsm#L43):

```
DEPRECATION WARNING: This path to Console.jsm is deprecated.  Please use Cu.import("resource://gre/modules/Console.jsm") to load this module.
You may find more details about this deprecation at: https://bugzil.la/912121
resource://gre/modules/devtools/Console.jsm 19 null
resource://tabcenter/verticaltabs.jsm 43 null
resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/pdehaan/dev/github/ff-tool/_temp/profiles/fftool.yBtyzD/extensions/tabcentertest1@mozilla.com.xpi!/bootstrap.js 97 startup
resource://gre/modules/addons/XPIProvider.jsm 4758 this.XPIProvider.callBootstrapMethod
resource://gre/modules/addons/XPIProvider.jsm 6218 AddonInstall.prototype.startInstall/<
resource://gre/modules/Task.jsm 319 TaskImpl_run
resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js 937 Handler.prototype.process
resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js 816 this.PromiseWalker.walkerLoop
```

<img width="1123" alt="browser_console_and_tech-gadgets" src="https://cloud.githubusercontent.com/assets/557895/14991462/45b661fc-1116-11e6-8937-dbb8321e89e5.png">

**Comment by bwinton** [comment]
Yeah, we should fix this.  It looks like `resource://gre/modules/Console.jsm` is available in Release now, so we can just go ahead and make the change.  (But it's not _that_ important, so I'm marking it as post-release.)

**Comment by ericawright** [comment]
this has been "fixed" console was not used, so was removed

**Comment by Croydon** [comment]
It is possible to use console without requiring anything anyway. I'm assuming that this wasn't the case a few years ago or something like that..

**Comment by bwinton** [comment]
Well, normally that's true, but not in the context this code is running in…
